USE [VLT_AX500105_P_BAK]
GO

/****** Object:  Table [dbo].[CUSTPACKINGSLIPTRANS]    Script Date: 13.05.2019 09:10:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CUSTPACKINGSLIPTRANS](
	[PACKINGSLIPID] [nvarchar](20) NOT NULL,
	[DELIVERYDATE] [datetime] NOT NULL,
	[LINENUM] [numeric](28, 12) NOT NULL,
	[INVENTTRANSID] [nvarchar](20) NOT NULL,
	[ITEMID] [nvarchar](20) NOT NULL,
	[EXTERNALITEMID] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](1000) NOT NULL,
	[ORDERED] [numeric](28, 12) NOT NULL,
	[QTY] [numeric](28, 12) NOT NULL,
	[REMAIN] [numeric](28, 12) NOT NULL,
	[SALESGROUP] [nvarchar](10) NOT NULL,
	[PRICEUNIT] [numeric](28, 12) NOT NULL,
	[DIMENSION] [nvarchar](10) NOT NULL,
	[DIMENSION2_] [nvarchar](10) NOT NULL,
	[DIMENSION3_] [nvarchar](10) NOT NULL,
	[VALUEMST] [numeric](28, 12) NOT NULL,
	[PARTDELIVERY] [int] NOT NULL,
	[SALESID] [nvarchar](20) NOT NULL,
	[SALESUNIT] [nvarchar](10) NOT NULL,
	[TRANSACTIONCODE] [nvarchar](10) NOT NULL,
	[TRANSPORT] [nvarchar](10) NOT NULL,
	[ORIGSALESID] [nvarchar](20) NOT NULL,
	[RETURNACTIONID] [nvarchar](10) NOT NULL,
	[LINEHEADER] [nvarchar](1000) NOT NULL,
	[INVENTDIMID] [nvarchar](20) NOT NULL,
	[STATPROCID] [nvarchar](10) NOT NULL,
	[PORT] [nvarchar](10) NOT NULL,
	[NUMBERSEQUENCEGROUP] [nvarchar](10) NOT NULL,
	[INTERCOMPANYINVENTTRANSID] [nvarchar](20) NOT NULL,
	[NVMODELDESCRIPTIONTEXT] [nvarchar](1000) NOT NULL,
	[NVMODELMAINDIM2] [nvarchar](10) NOT NULL,
	[NVMODELMAINDIM1] [nvarchar](10) NOT NULL,
	[NVCONFIGSTRING] [nvarchar](100) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECID] [bigint] NOT NULL,
	[NVMARKUPPERCENT] [numeric](28, 12) NOT NULL,
	[NVAUTOLINE] [int] NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[DLVCOUNTY] [nvarchar](10) NOT NULL,
	[DLVSTATE] [nvarchar](10) NOT NULL,
	[DLVCOUNTRYREGIONID] [nvarchar](10) NOT NULL,
	[COUNTRYREGIONOFSHIPMENT] [nvarchar](10) NOT NULL,
	[INVENTREFID] [nvarchar](20) NOT NULL,
	[STATVALUEMST] [numeric](28, 12) NOT NULL,
	[INTRASTATDISPATCHID] [nvarchar](20) NOT NULL,
	[INVENTQTY] [numeric](28, 12) NOT NULL,
	[INVENTREFTRANSID] [nvarchar](20) NOT NULL,
	[DELIVERYTYPE] [int] NOT NULL,
	[INVENTREFTYPE] [int] NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[SALESBOQID_ADDON] [nvarchar](20) NOT NULL,
 CONSTRAINT [I_072RECID] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [PACKINGSLIPID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DELIVERYDATE]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [LINENUM]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [INVENTTRANSID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [ITEMID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [EXTERNALITEMID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [NAME]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [ORDERED]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [QTY]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [REMAIN]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [SALESGROUP]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [PRICEUNIT]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [DIMENSION]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [DIMENSION2_]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [DIMENSION3_]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [VALUEMST]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [PARTDELIVERY]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [SALESID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [SALESUNIT]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [TRANSACTIONCODE]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [TRANSPORT]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [ORIGSALESID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [RETURNACTIONID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [LINEHEADER]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [INVENTDIMID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [STATPROCID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [PORT]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [NUMBERSEQUENCEGROUP]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [INTERCOMPANYINVENTTRANSID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [NVMODELDESCRIPTIONTEXT]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [NVMODELMAINDIM2]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [NVMODELMAINDIM1]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [NVCONFIGSTRING]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [NVMARKUPPERCENT]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [NVAUTOLINE]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [DLVCOUNTY]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [DLVSTATE]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [DLVCOUNTRYREGIONID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [COUNTRYREGIONOFSHIPMENT]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [INVENTREFID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [STATVALUEMST]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [INTRASTATDISPATCHID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [INVENTQTY]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [INVENTREFTRANSID]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [DELIVERYTYPE]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ((0)) FOR [INVENTREFTYPE]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS] ADD  DEFAULT ('') FOR [SALESBOQID_ADDON]
GO

ALTER TABLE [dbo].[CUSTPACKINGSLIPTRANS]  WITH NOCHECK ADD CHECK  (([RECID]<>(0)))
GO


