USE [VLT_AX500105_P_BAK]
GO

/****** Object:  Table [dbo].[SALESTABLE]    Script Date: 13.05.2019 09:09:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SALESTABLE](
	[SALESID] [nvarchar](20) NOT NULL,
	[SALESNAME] [nvarchar](60) NOT NULL,
	[RESERVATION] [int] NOT NULL,
	[CUSTACCOUNT] [nvarchar](20) NOT NULL,
	[INVOICEACCOUNT] [nvarchar](20) NOT NULL,
	[DELIVERYDATE] [datetime] NOT NULL,
	[DELIVERYADDRESS] [nvarchar](250) NOT NULL,
	[URL] [nvarchar](255) NOT NULL,
	[PURCHORDERFORMNUM] [nvarchar](20) NOT NULL,
	[SALESTAKER] [nvarchar](20) NOT NULL,
	[SALESGROUP] [nvarchar](10) NOT NULL,
	[FREIGHTSLIPTYPE] [int] NOT NULL,
	[DOCUMENTSTATUS] [int] NOT NULL,
	[CURRENCYCODE] [nvarchar](3) NOT NULL,
	[PAYMENT] [nvarchar](10) NOT NULL,
	[CASHDISC] [nvarchar](10) NOT NULL,
	[TAXGROUP] [nvarchar](10) NOT NULL,
	[LINEDISC] [nvarchar](10) NOT NULL,
	[CUSTGROUP] [nvarchar](10) NOT NULL,
	[DISCPERCENT] [numeric](28, 12) NOT NULL,
	[DIMENSION] [nvarchar](10) NOT NULL,
	[DIMENSION2_] [nvarchar](10) NOT NULL,
	[DIMENSION3_] [nvarchar](10) NOT NULL,
	[PRICEGROUPID] [nvarchar](10) NOT NULL,
	[MULTILINEDISC] [nvarchar](10) NOT NULL,
	[ENDDISC] [nvarchar](10) NOT NULL,
	[CUSTOMERREF] [nvarchar](60) NOT NULL,
	[LISTCODE] [int] NOT NULL,
	[DLVTERM] [nvarchar](10) NOT NULL,
	[DLVMODE] [nvarchar](10) NOT NULL,
	[PURCHID] [nvarchar](20) NOT NULL,
	[SALESSTATUS] [int] NOT NULL,
	[MARKUPGROUP] [nvarchar](10) NOT NULL,
	[SALESTYPE] [int] NOT NULL,
	[SALESPOOLID] [nvarchar](10) NOT NULL,
	[POSTINGPROFILE] [nvarchar](10) NOT NULL,
	[TRANSACTIONCODE] [nvarchar](10) NOT NULL,
	[DELIVERYZIPCODE] [nvarchar](10) NOT NULL,
	[DELIVERYCOUNTY] [nvarchar](10) NOT NULL,
	[DELIVERYCOUNTRYREGIONID] [nvarchar](10) NOT NULL,
	[SETTLEVOUCHER] [int] NOT NULL,
	[DELIVERYSTATE] [nvarchar](10) NOT NULL,
	[DELIVERYNAME] [nvarchar](60) NOT NULL,
	[ONETIMECUSTOMER] [int] NOT NULL,
	[COMMISSIONGROUP] [nvarchar](10) NOT NULL,
	[PAYMENTSCHED] [nvarchar](30) NOT NULL,
	[EMAIL] [nvarchar](80) NOT NULL,
	[FREIGHTZONE] [nvarchar](10) NOT NULL,
	[RETURNITEMNUM] [nvarchar](10) NOT NULL,
	[CONTACTPERSONID] [nvarchar](20) NOT NULL,
	[DEADLINE] [datetime] NOT NULL,
	[INVENTLOCATIONID] [nvarchar](10) NOT NULL,
	[VATNUM] [nvarchar](20) NOT NULL,
	[PORT] [nvarchar](10) NOT NULL,
	[INCLTAX] [int] NOT NULL,
	[NUMBERSEQUENCEGROUP] [nvarchar](10) NOT NULL,
	[FIXEDEXCHRATE] [numeric](28, 12) NOT NULL,
	[LANGUAGEID] [nvarchar](7) NOT NULL,
	[AUTOSUMMARYMODULETYPE] [int] NOT NULL,
	[GIROTYPE] [int] NOT NULL,
	[SALESORIGINID] [nvarchar](10) NOT NULL,
	[ESTIMATE] [numeric](28, 12) NOT NULL,
	[TRANSPORT] [nvarchar](10) NOT NULL,
	[DEL_PRINTMODULETYPE] [int] NOT NULL,
	[PAYMMODE] [nvarchar](10) NOT NULL,
	[PAYMSPEC] [nvarchar](10) NOT NULL,
	[FIXEDDUEDATE] [datetime] NOT NULL,
	[DELIVERYCITY] [nvarchar](60) NOT NULL,
	[DELIVERYSTREET] [nvarchar](250) NOT NULL,
	[EXPORTREASON] [nvarchar](30) NOT NULL,
	[STATPROCID] [nvarchar](10) NOT NULL,
	[DEL_REFDLVZIPCODE] [bigint] NOT NULL,
	[SALESRESPONSIBLE] [nvarchar](20) NOT NULL,
	[SMMSALESAMOUNTTOTAL] [numeric](28, 12) NOT NULL,
	[NVMONTREQTRUPPID] [nvarchar](10) NOT NULL,
	[NVKLZFERTINFO] [nvarchar](15) NOT NULL,
	[NVKLZAVINFO] [nvarchar](5) NOT NULL,
	[NVKLZBESTINFO] [nvarchar](15) NOT NULL,
	[NVKLZFERTDATUM] [datetime] NOT NULL,
	[NVKLZAVDATUM] [datetime] NOT NULL,
	[NVKLZBESTDATUM] [datetime] NOT NULL,
	[NVKLZFERTSTAT] [nvarchar](1) NOT NULL,
	[NVKLZAVSTAT] [nvarchar](1) NOT NULL,
	[NVKLZBESTSTAT] [nvarchar](2) NOT NULL,
	[NVKLZCOLLI] [int] NOT NULL,
	[NVKLZETIKGEDRUCKT] [int] NOT NULL,
	[NVKLZABGEDRUCKT] [int] NOT NULL,
	[NVKLZWAGENID] [nvarchar](20) NOT NULL,
	[NVMONTINFO] [nvarchar](120) NOT NULL,
	[NVMONTREQTIME] [int] NOT NULL,
	[NVMONTREQDATE] [datetime] NOT NULL,
	[NVKLZPRINTINCLTAX] [int] NOT NULL,
	[NVMONTREQISFIX] [int] NOT NULL,
	[NVMONTSTATUSID] [nvarchar](10) NOT NULL,
	[NVMONTINFOPLANNING] [nvarchar](1000) NOT NULL,
	[NVWOPLANPRODDATUM] [datetime] NOT NULL,
	[NVWOPLANBEMERKUNG] [nvarchar](15) NOT NULL,
	[NVTELEFAX] [nvarchar](80) NOT NULL,
	[NVFAXTIME2SEND] [int] NOT NULL,
	[NVCOMMTYPECONFIRM] [int] NOT NULL,
	[NVCOMMTYPEQUOTATION] [int] NOT NULL,
	[NVQUOTSTATDATE] [datetime] NOT NULL,
	[NVQUOTSTATID] [nvarchar](5) NOT NULL,
	[NVAGENTACCOUNT] [nvarchar](10) NOT NULL,
	[NVCUSTACCOUNTTYPE] [int] NOT NULL,
	[NVPOPRINTED] [int] NOT NULL,
	[NVDESTINATIONCODEID] [nvarchar](10) NOT NULL,
	[NVPRODTEXT] [nvarchar](1000) NOT NULL,
	[NVCOMPANYID] [nvarchar](10) NOT NULL,
	[NVPACKEREMPLID] [nvarchar](20) NOT NULL,
	[NVRESTDLVDATE] [datetime] NOT NULL,
	[NVRESTDLVTEXT] [nvarchar](100) NOT NULL,
	[NVPARTINVOICENUM] [int] NOT NULL,
	[NVPARTINVOICE] [int] NOT NULL,
	[NVINVOICETYPE] [int] NOT NULL,
	[NVMONTPLANDATE] [datetime] NOT NULL,
	[NVMONTPLANFIX] [int] NOT NULL,
	[NVMONTAVISDATE] [datetime] NOT NULL,
	[NVMONTAVISCOMMTYPE] [int] NOT NULL,
	[NVMONTPLANNING] [int] NOT NULL,
	[NVMONTPLANCONFIRMED] [int] NOT NULL,
	[NVMONTPLANTIME] [int] NOT NULL,
	[NVMONTPLANTRUPPID] [nvarchar](10) NOT NULL,
	[NVMONTCONTACTNAME] [nvarchar](60) NOT NULL,
	[NVMONTCONTACTPHONE] [nvarchar](60) NOT NULL,
	[NVMONTPLANHOURS] [numeric](28, 12) NOT NULL,
	[NVMONTPLANNED] [int] NOT NULL,
	[NVMONTFINISHED] [int] NOT NULL,
	[NVMONTCONTACTEMAIL] [nvarchar](80) NOT NULL,
	[NVMONTCONTACTFAX] [nvarchar](80) NOT NULL,
	[NVMONTAVISSTATUS] [int] NOT NULL,
	[NVMONTAVISNAME] [nvarchar](60) NOT NULL,
	[NVMONTAVISADDRESS] [nvarchar](250) NOT NULL,
	[NVGUARANTEEEND] [datetime] NOT NULL,
	[NVLIABILITYLETTERFROM] [datetime] NOT NULL,
	[NVLIABILITYLETTERTO] [datetime] NOT NULL,
	[NVPRODBLOCKED] [int] NOT NULL,
	[NVDELIVERYDATETYPE] [int] NOT NULL,
	[NVDRAWING4PROD] [int] NOT NULL,
	[NVDRAWING4MONT] [int] NOT NULL,
	[NVMONTAGEID] [nvarchar](10) NOT NULL,
	[NVINVOICINGBLOCKED] [int] NOT NULL,
	[NVINVOICINGINFO] [nvarchar](100) NOT NULL,
	[NVINVOICINGCONTROLDATE] [datetime] NOT NULL,
	[NVLIABILITYAMT] [numeric](28, 12) NOT NULL,
	[NVPROJECTID] [nvarchar](10) NOT NULL,
	[DEL_NVMONTORDERTYPE] [int] NOT NULL,
	[NVINVOICINGCONTROLSHOWAGAIN] [datetime] NOT NULL,
	[NVINVOICINGCONTROLUSERID] [nvarchar](5) NOT NULL,
	[MODIFIEDDATETIME] [datetime] NOT NULL,
	[DEL_MODIFIEDTIME] [int] NOT NULL,
	[MODIFIEDBY] [nvarchar](5) NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[DEL_CREATEDTIME] [int] NOT NULL,
	[CREATEDBY] [nvarchar](5) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECID] [bigint] NOT NULL,
	[NVBAXORDERID] [nvarchar](10) NOT NULL,
	[NVBAXCHAINID] [nvarchar](10) NOT NULL,
	[NVDELIVERED] [int] NOT NULL,
	[NVDELIVEREDDATE] [datetime] NOT NULL,
	[NVCOLLECTAVIS1] [datetime] NOT NULL,
	[NVCOLLECTAVIS2] [datetime] NOT NULL,
	[NVCOLLECTAVISTXT] [nvarchar](100) NOT NULL,
	[NVDELIVEREDSCANSHOW] [int] NOT NULL,
	[NVDELIVEREDSCANORDER] [int] NOT NULL,
	[NVDELIVEREDSCANUSR] [nvarchar](10) NOT NULL,
	[NVCOLLECTLISTHIDE] [int] NOT NULL,
	[NVDELIVERYNOTES] [nvarchar](100) NOT NULL,
	[NVCUTLABELSPRINTED] [int] NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[INTERCOMPANYORIGINALSALESID] [nvarchar](20) NOT NULL,
	[INTERCOMPANYORIGINALCUSTACCO22] [nvarchar](20) NOT NULL,
	[CASHDISCPERCENT] [numeric](28, 12) NOT NULL,
	[ADDRESSREFTABLEID] [int] NOT NULL,
	[EINVOICELINESPEC] [int] NOT NULL,
	[DLVREASON] [nvarchar](10) NOT NULL,
	[QUOTATIONID] [nvarchar](20) NOT NULL,
	[DEL_DELIVERYDATECONTROL] [int] NOT NULL,
	[RECEIPTDATEREQUESTED] [datetime] NOT NULL,
	[RECEIPTDATECONFIRMED] [datetime] NOT NULL,
	[SHIPPINGDATEREQUESTED] [datetime] NOT NULL,
	[SHIPPINGDATECONFIRMED] [datetime] NOT NULL,
	[DEL_CORRECTIVEREASON] [ntext] NULL,
	[DEL_CORRECTEDINVOICEID] [nvarchar](20) NOT NULL,
	[DEL_PARENTSALESID] [nvarchar](20) NOT NULL,
	[EINVOICEACCOUNTCODE] [nvarchar](35) NOT NULL,
	[ITEMTAGGING] [int] NOT NULL,
	[CASETAGGING] [int] NOT NULL,
	[PALLETTAGGING] [int] NOT NULL,
	[ADDRESSREFRECID] [bigint] NOT NULL,
	[CUSTINVOICEID] [nvarchar](20) NOT NULL,
	[INVENTSITEID] [nvarchar](10) NOT NULL,
	[CREDITCARDCUSTREFID] [bigint] NOT NULL,
	[SHIPCARRIERACCOUNT] [nvarchar](25) NOT NULL,
	[SHIPCARRIERID] [nvarchar](10) NOT NULL,
	[SHIPCARRIERFUELSURCHARGE] [int] NOT NULL,
	[SHIPCARRIERBLINDSHIPMENT] [int] NOT NULL,
	[CREDITCARDPROCESSORTRANSACT140] [nvarchar](48) NOT NULL,
	[SHIPCARRIERDELIVERYCONTACT] [nvarchar](60) NOT NULL,
	[CREDITCARDAPPROVALAMOUNT] [numeric](28, 12) NOT NULL,
	[CREDITCARDAUTHORIZATION] [nvarchar](20) NOT NULL,
	[RETURNDEADLINE] [datetime] NOT NULL,
	[RETURNREPLACEMENTID] [nvarchar](20) NOT NULL,
	[RETURNSTATUS] [int] NOT NULL,
	[RETURNREASONCODEID] [nvarchar](10) NOT NULL,
	[CREDITCARDAUTHORIZATIONERROR] [int] NOT NULL,
	[SHIPCARRIERACCOUNTCODE] [nvarchar](20) NOT NULL,
	[RETURNREPLACEMENTCREATED] [int] NOT NULL,
	[SHIPCARRIERDLVTYPE] [int] NOT NULL,
	[ATPINCLPLANNEDORDERS] [int] NOT NULL,
	[ATPTIMEFENCE] [int] NOT NULL,
	[DELIVERYDATECONTROLTYPE] [int] NOT NULL,
	[SHIPCARRIEREXPEDITEDSHIPMENT] [int] NOT NULL,
	[SHIPCARRIERRESIDENTIAL] [int] NOT NULL,
	[NVQUOTECONVERTED] [int] NOT NULL,
	[COVSTATUS] [int] NOT NULL,
	[PROJID] [nvarchar](10) NOT NULL,
	[SALESUNITID] [nvarchar](20) NOT NULL,
	[SMMCAMPAIGNID] [nvarchar](10) NOT NULL,
	[NVRECEIPTTIMEREQAFTER] [int] NOT NULL,
	[NVRECEIPTTIMEREQBEFORE] [int] NOT NULL,
	[NVSALESGROUP2] [nvarchar](10) NOT NULL,
	[NVCOMMISSIONGROUP2] [nvarchar](10) NOT NULL,
	[MAINSALESID_ADDON] [nvarchar](20) NOT NULL,
	[MAINSALESORDER_ADDON] [int] NOT NULL,
	[OBJECTINVOICE_ADDON] [int] NOT NULL,
	[OBJECTORDERENDINVOICEAPPR30100] [int] NOT NULL,
	[OBJECTORDERENDINVOICEAPPR30101] [nvarchar](60) NOT NULL,
	[NVGAUZELABELSPRINTED] [int] NOT NULL,
	[NVEMAILSC_ADDON] [nvarchar](80) NOT NULL,
	[DELIVERYDATE1] [datetime] NOT NULL,
	[OBJECTORDERINVOICEAPPROVE30105] [datetime] NOT NULL,
	[OBJECTORDERINVOICEAPPROVA30106] [nvarchar](20) NOT NULL,
	[PRINTDISCOUNTEDPIECEPRICE30107] [int] NOT NULL,
	[NVCOMMTYPESALESINVOICE] [int] NOT NULL,
	[EMAILSALESINVOICE_ADDON] [nvarchar](80) NOT NULL,
	[DIRECTDEBITMANDATE] [bigint] NOT NULL,
	[TCMSALESGROUP3] [nvarchar](10) NOT NULL,
	[TCMCOMMISSIONGROUP3] [nvarchar](10) NOT NULL,
	[TCMVEHICLECLASSIFICATION] [int] NOT NULL,
	[VLT_INVENTJOURNALIDPROJECT] [nvarchar](10) NOT NULL,
	[VLT_SALESORDERPRODREGSTATUS] [int] NOT NULL,
	[VLT_SALESORDERPRODREGDATETIME] [datetime] NOT NULL,
	[VLT_SALESORDERPRODREGTZID30117] [int] NOT NULL,
	[VLT_SALESORDERPRODREGEMPLID] [nvarchar](20) NOT NULL,
	[VLT_SALESORDERPRODREGDATE30119] [datetime] NOT NULL,
	[VLT_SALESORDERPRODREGTZID30119] [int] NOT NULL,
	[VLT_SALESORDERPRODREGEMPL30120] [nvarchar](20) NOT NULL,
	[VLT_SALESORDERPRODREGDATE30121] [datetime] NOT NULL,
	[VLT_SALESORDERPRODREGTZID30121] [int] NOT NULL,
	[VLT_SALESORDERPRODREGEMPL30122] [nvarchar](20) NOT NULL,
	[VLT_SALESORDERPRODREGDATE30123] [datetime] NOT NULL,
	[VLT_SALESORDERPRODREGTZID30123] [int] NOT NULL,
	[VLT_SALESORDERPRODREGEMPL30124] [nvarchar](20) NOT NULL,
	[VLT_SALESORDERPRODREGDATE30125] [datetime] NOT NULL,
	[VLT_SALESORDERPRODREGTZID30125] [int] NOT NULL,
	[VLT_SUPPRESSCAPACITYCHECK] [int] NOT NULL,
	[VLT_PROJMONTTRUPPID] [nvarchar](10) NOT NULL,
	[VLT_PURCHINFOTXT] [nvarchar](1000) NOT NULL,
	[VLT_ISSALESORDERTEST] [int] NOT NULL,
 CONSTRAINT [I_366SALESIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[SALESID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SALESID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SALESNAME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [RESERVATION]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [CUSTACCOUNT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [INVOICEACCOUNT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DELIVERYDATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DELIVERYADDRESS]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [URL]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [PURCHORDERFORMNUM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SALESTAKER]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SALESGROUP]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [FREIGHTSLIPTYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [DOCUMENTSTATUS]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [CURRENCYCODE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [PAYMENT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [CASHDISC]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [TAXGROUP]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [LINEDISC]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [CUSTGROUP]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [DISCPERCENT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DIMENSION]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DIMENSION2_]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DIMENSION3_]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [PRICEGROUPID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [MULTILINEDISC]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [ENDDISC]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [CUSTOMERREF]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [LISTCODE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DLVTERM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DLVMODE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [PURCHID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [SALESSTATUS]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [MARKUPGROUP]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [SALESTYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SALESPOOLID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [POSTINGPROFILE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [TRANSACTIONCODE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DELIVERYZIPCODE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DELIVERYCOUNTY]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DELIVERYCOUNTRYREGIONID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [SETTLEVOUCHER]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DELIVERYSTATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DELIVERYNAME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [ONETIMECUSTOMER]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [COMMISSIONGROUP]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [PAYMENTSCHED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [EMAIL]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [FREIGHTZONE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [RETURNITEMNUM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [CONTACTPERSONID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DEADLINE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [INVENTLOCATIONID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [VATNUM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [PORT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [INCLTAX]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NUMBERSEQUENCEGROUP]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [FIXEDEXCHRATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [LANGUAGEID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [AUTOSUMMARYMODULETYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [GIROTYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SALESORIGINID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [ESTIMATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [TRANSPORT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [DEL_PRINTMODULETYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [PAYMMODE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [PAYMSPEC]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [FIXEDDUEDATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DELIVERYCITY]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DELIVERYSTREET]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [EXPORTREASON]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [STATPROCID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [DEL_REFDLVZIPCODE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SALESRESPONSIBLE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [SMMSALESAMOUNTTOTAL]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTREQTRUPPID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVKLZFERTINFO]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVKLZAVINFO]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVKLZBESTINFO]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVKLZFERTDATUM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVKLZAVDATUM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVKLZBESTDATUM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVKLZFERTSTAT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVKLZAVSTAT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVKLZBESTSTAT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVKLZCOLLI]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVKLZETIKGEDRUCKT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVKLZABGEDRUCKT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVKLZWAGENID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTINFO]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTREQTIME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVMONTREQDATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVKLZPRINTINCLTAX]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTREQISFIX]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTSTATUSID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTINFOPLANNING]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVWOPLANPRODDATUM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVWOPLANBEMERKUNG]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVTELEFAX]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVFAXTIME2SEND]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVCOMMTYPECONFIRM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVCOMMTYPEQUOTATION]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVQUOTSTATDATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVQUOTSTATID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVAGENTACCOUNT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVCUSTACCOUNTTYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVPOPRINTED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVDESTINATIONCODEID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVPRODTEXT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVCOMPANYID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVPACKEREMPLID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVRESTDLVDATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVRESTDLVTEXT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVPARTINVOICENUM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVPARTINVOICE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVINVOICETYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVMONTPLANDATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTPLANFIX]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVMONTAVISDATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTAVISCOMMTYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTPLANNING]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTPLANCONFIRMED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTPLANTIME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTPLANTRUPPID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTCONTACTNAME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTCONTACTPHONE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTPLANHOURS]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTPLANNED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTFINISHED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTCONTACTEMAIL]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTCONTACTFAX]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVMONTAVISSTATUS]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTAVISNAME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTAVISADDRESS]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVGUARANTEEEND]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVLIABILITYLETTERFROM]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVLIABILITYLETTERTO]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVPRODBLOCKED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVDELIVERYDATETYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVDRAWING4PROD]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVDRAWING4MONT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVMONTAGEID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVINVOICINGBLOCKED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVINVOICINGINFO]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVINVOICINGCONTROLDATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVLIABILITYAMT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVPROJECTID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [DEL_NVMONTORDERTYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVINVOICINGCONTROLSHOWAGAIN]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVINVOICINGCONTROLUSERID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [MODIFIEDDATETIME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [DEL_MODIFIEDTIME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('?') FOR [MODIFIEDBY]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [DEL_CREATEDTIME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('?') FOR [CREATEDBY]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVBAXORDERID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVBAXCHAINID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVDELIVERED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVDELIVEREDDATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVCOLLECTAVIS1]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [NVCOLLECTAVIS2]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVCOLLECTAVISTXT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVDELIVEREDSCANSHOW]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVDELIVEREDSCANORDER]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVDELIVEREDSCANUSR]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVCOLLECTLISTHIDE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVDELIVERYNOTES]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVCUTLABELSPRINTED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [INTERCOMPANYORIGINALSALESID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [INTERCOMPANYORIGINALCUSTACCO22]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [CASHDISCPERCENT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [ADDRESSREFTABLEID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [EINVOICELINESPEC]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DLVREASON]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [QUOTATIONID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [DEL_DELIVERYDATECONTROL]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [RECEIPTDATEREQUESTED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [RECEIPTDATECONFIRMED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [SHIPPINGDATEREQUESTED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [SHIPPINGDATECONFIRMED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT (NULL) FOR [DEL_CORRECTIVEREASON]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DEL_CORRECTEDINVOICEID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [DEL_PARENTSALESID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [EINVOICEACCOUNTCODE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [ITEMTAGGING]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [CASETAGGING]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [PALLETTAGGING]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [ADDRESSREFRECID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [CUSTINVOICEID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [INVENTSITEID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [CREDITCARDCUSTREFID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SHIPCARRIERACCOUNT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SHIPCARRIERID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [SHIPCARRIERFUELSURCHARGE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [SHIPCARRIERBLINDSHIPMENT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [CREDITCARDPROCESSORTRANSACT140]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SHIPCARRIERDELIVERYCONTACT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [CREDITCARDAPPROVALAMOUNT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [CREDITCARDAUTHORIZATION]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [RETURNDEADLINE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [RETURNREPLACEMENTID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [RETURNSTATUS]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [RETURNREASONCODEID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [CREDITCARDAUTHORIZATIONERROR]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SHIPCARRIERACCOUNTCODE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [RETURNREPLACEMENTCREATED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [SHIPCARRIERDLVTYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [ATPINCLPLANNEDORDERS]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [ATPTIMEFENCE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [DELIVERYDATECONTROLTYPE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [SHIPCARRIEREXPEDITEDSHIPMENT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [SHIPCARRIERRESIDENTIAL]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVQUOTECONVERTED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [COVSTATUS]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [PROJID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SALESUNITID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [SMMCAMPAIGNID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVRECEIPTTIMEREQAFTER]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVRECEIPTTIMEREQBEFORE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVSALESGROUP2]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVCOMMISSIONGROUP2]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [MAINSALESID_ADDON]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [MAINSALESORDER_ADDON]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [OBJECTINVOICE_ADDON]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [OBJECTORDERENDINVOICEAPPR30100]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [OBJECTORDERENDINVOICEAPPR30101]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVGAUZELABELSPRINTED]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [NVEMAILSC_ADDON]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DELIVERYDATE1]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [OBJECTORDERINVOICEAPPROVE30105]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [OBJECTORDERINVOICEAPPROVA30106]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [PRINTDISCOUNTEDPIECEPRICE30107]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [NVCOMMTYPESALESINVOICE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [EMAILSALESINVOICE_ADDON]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [DIRECTDEBITMANDATE]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [TCMSALESGROUP3]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [TCMCOMMISSIONGROUP3]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [TCMVEHICLECLASSIFICATION]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [VLT_INVENTJOURNALIDPROJECT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [VLT_SALESORDERPRODREGSTATUS]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [VLT_SALESORDERPRODREGDATETIME]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((37001)) FOR [VLT_SALESORDERPRODREGTZID30117]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [VLT_SALESORDERPRODREGEMPLID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [VLT_SALESORDERPRODREGDATE30119]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((37001)) FOR [VLT_SALESORDERPRODREGTZID30119]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [VLT_SALESORDERPRODREGEMPL30120]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [VLT_SALESORDERPRODREGDATE30121]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((37001)) FOR [VLT_SALESORDERPRODREGTZID30121]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [VLT_SALESORDERPRODREGEMPL30122]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [VLT_SALESORDERPRODREGDATE30123]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((37001)) FOR [VLT_SALESORDERPRODREGTZID30123]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [VLT_SALESORDERPRODREGEMPL30124]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [VLT_SALESORDERPRODREGDATE30125]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((37001)) FOR [VLT_SALESORDERPRODREGTZID30125]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [VLT_SUPPRESSCAPACITYCHECK]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [VLT_PROJMONTTRUPPID]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ('') FOR [VLT_PURCHINFOTXT]
GO

ALTER TABLE [dbo].[SALESTABLE] ADD  DEFAULT ((0)) FOR [VLT_ISSALESORDERTEST]
GO

ALTER TABLE [dbo].[SALESTABLE]  WITH NOCHECK ADD CHECK  (([RECID]<>(0)))
GO

