USE [VLT_AX500105_P_BAK]
GO

/****** Object:  Table [dbo].[CUSTINVOICEJOUR]    Script Date: 13.05.2019 09:11:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CUSTINVOICEJOUR](
	[CUSTGROUP] [nvarchar](10) NOT NULL,
	[REFNUM] [int] NOT NULL,
	[SALESID] [nvarchar](20) NOT NULL,
	[ORDERACCOUNT] [nvarchar](20) NOT NULL,
	[INVOICEACCOUNT] [nvarchar](20) NOT NULL,
	[INVOICEDATE] [datetime] NOT NULL,
	[DUEDATE] [datetime] NOT NULL,
	[CASHDISC] [numeric](28, 12) NOT NULL,
	[CASHDISCDATE] [datetime] NOT NULL,
	[QTY] [numeric](28, 12) NOT NULL,
	[VOLUME] [numeric](28, 12) NOT NULL,
	[WEIGHT] [numeric](28, 12) NOT NULL,
	[SUMLINEDISC] [numeric](28, 12) NOT NULL,
	[SALESBALANCE] [numeric](28, 12) NOT NULL,
	[ENDDISC] [numeric](28, 12) NOT NULL,
	[INVOICEAMOUNT] [numeric](28, 12) NOT NULL,
	[CURRENCYCODE] [nvarchar](3) NOT NULL,
	[EXCHRATE] [numeric](28, 12) NOT NULL,
	[SALESADMINISTRATOR] [nvarchar](20) NOT NULL,
	[INVOICEID] [nvarchar](20) NOT NULL,
	[LEDGERVOUCHER] [nvarchar](20) NOT NULL,
	[UPDATED] [int] NOT NULL,
	[DIMENSION] [nvarchar](10) NOT NULL,
	[DIMENSION2_] [nvarchar](10) NOT NULL,
	[DIMENSION3_] [nvarchar](10) NOT NULL,
	[ONACCOUNTAMOUNT] [numeric](28, 12) NOT NULL,
	[TAXPRINTONINVOICE] [int] NOT NULL,
	[LISTCODE] [int] NOT NULL,
	[DEL_PRINTED] [int] NOT NULL,
	[DOCUMENTNUM] [nvarchar](20) NOT NULL,
	[DOCUMENTDATE] [datetime] NOT NULL,
	[INTRASTATDISPATCH] [nvarchar](20) NOT NULL,
	[DELIVERYNAME] [nvarchar](60) NOT NULL,
	[DELIVERYADDRESS] [nvarchar](250) NOT NULL,
	[PURCHASEORDER] [nvarchar](20) NOT NULL,
	[DLVTERM] [nvarchar](10) NOT NULL,
	[DLVMODE] [nvarchar](10) NOT NULL,
	[PAYMENT] [nvarchar](10) NOT NULL,
	[CASHDISCCODE] [nvarchar](10) NOT NULL,
	[INVOICEROUNDOFF] [numeric](28, 12) NOT NULL,
	[SUMMARKUP] [numeric](28, 12) NOT NULL,
	[RETURNITEMNUM] [nvarchar](10) NOT NULL,
	[POSTINGPROFILE] [nvarchar](10) NOT NULL,
	[BACKORDER] [int] NOT NULL,
	[DLVZIPCODE] [nvarchar](10) NOT NULL,
	[DLVCOUNTY] [nvarchar](10) NOT NULL,
	[DLVCOUNTRYREGIONID] [nvarchar](10) NOT NULL,
	[DLVSTATE] [nvarchar](10) NOT NULL,
	[TAXGROUP] [nvarchar](10) NOT NULL,
	[TAXITEMGROUP] [nvarchar](10) NOT NULL,
	[DEL_TAXSPECIFYTOTAL] [int] NOT NULL,
	[TAXSPECIFYBYLINE] [int] NOT NULL,
	[ONETIMECUSTOMER] [int] NOT NULL,
	[PAYMENTSCHED] [nvarchar](30) NOT NULL,
	[SUMTAX] [numeric](28, 12) NOT NULL,
	[SALESTYPE] [int] NOT NULL,
	[PARMID] [nvarchar](20) NOT NULL,
	[EUSALESLIST] [nvarchar](20) NOT NULL,
	[EXCHRATESECONDARY] [numeric](28, 12) NOT NULL,
	[TRIANGULATION] [int] NOT NULL,
	[CUSTOMERREF] [nvarchar](60) NOT NULL,
	[VATNUM] [nvarchar](20) NOT NULL,
	[NUMBERSEQUENCEGROUP] [nvarchar](10) NOT NULL,
	[LANGUAGEID] [nvarchar](7) NOT NULL,
	[INCLTAX] [int] NOT NULL,
	[LOG] [nvarchar](255) NOT NULL,
	[PAYMDAYID] [nvarchar](10) NOT NULL,
	[INVOICINGNAME] [nvarchar](60) NOT NULL,
	[INVOICINGADDRESS] [nvarchar](250) NOT NULL,
	[INVZIPCODE] [nvarchar](10) NOT NULL,
	[INVCOUNTY] [nvarchar](10) NOT NULL,
	[INVCOUNTRYREGIONID] [nvarchar](10) NOT NULL,
	[INVSTATE] [nvarchar](10) NOT NULL,
	[GIROTYPE] [int] NOT NULL,
	[CONTACTPERSONID] [nvarchar](20) NOT NULL,
	[SALESORIGINID] [nvarchar](10) NOT NULL,
	[BILLOFLADINGID] [nvarchar](17) NOT NULL,
	[INVENTLOCATIONID] [nvarchar](10) NOT NULL,
	[FIXEDDUEDATE] [datetime] NOT NULL,
	[DELIVERYCITY] [nvarchar](60) NOT NULL,
	[DELIVERYSTREET] [nvarchar](250) NOT NULL,
	[INVOICECITY] [nvarchar](60) NOT NULL,
	[INVOICESTREET] [nvarchar](250) NOT NULL,
	[DEL_PRINTORIGINALS] [int] NOT NULL,
	[DEL_PRINTCOPIES] [int] NOT NULL,
	[INVOICEAMOUNTMST] [numeric](28, 12) NOT NULL,
	[INVOICEROUNDOFFMST] [numeric](28, 12) NOT NULL,
	[SUMMARKUPMST] [numeric](28, 12) NOT NULL,
	[SUMLINEDISCMST] [numeric](28, 12) NOT NULL,
	[ENDDISCMST] [numeric](28, 12) NOT NULL,
	[SALESBALANCEMST] [numeric](28, 12) NOT NULL,
	[SUMTAXMST] [numeric](28, 12) NOT NULL,
	[DEL_REFDLVZIPCODE] [bigint] NOT NULL,
	[DEL_REFINVZIPCODE] [bigint] NOT NULL,
	[DEL_NPIBANKINGPAYMID] [nvarchar](200) NOT NULL,
	[NVKLZENDDISCPCT] [numeric](28, 12) NOT NULL,
	[NVKLZPRINTINCLTAX] [int] NOT NULL,
	[NVAGENTACCOUNT] [nvarchar](10) NOT NULL,
	[NVDESTINATIONCODEID] [nvarchar](10) NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[DEL_CREATEDTIME] [int] NOT NULL,
	[CREATEDBY] [nvarchar](5) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECID] [bigint] NOT NULL,
	[NVCOMPANYID] [nvarchar](10) NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[PREPAYMENT] [int] NOT NULL,
	[EINVOICELINESPECIFIC] [int] NOT NULL,
	[DEL_CORRECTEDINVOICEID] [nvarchar](20) NOT NULL,
	[DEL_CORRECTIVEREASON] [ntext] NULL,
	[EINVOICEACCOUNTCODE] [nvarchar](35) NOT NULL,
	[RETURNREASONCODEID] [nvarchar](10) NOT NULL,
	[PRINTMGMTSITEID] [nvarchar](10) NOT NULL,
	[RETURNSTATUS] [int] NOT NULL,
	[PRINTEDORIGINALS] [int] NOT NULL,
	[PROFORMA] [int] NOT NULL,
	[REVERSECHARGE_UK] [numeric](28, 12) NOT NULL,
	[PAYMID] [nvarchar](200) NOT NULL,
	[COVSTATUS] [int] NOT NULL,
	[NVINVOICETYPE_ADDON] [int] NOT NULL,
	[NVPARTINVOICENUM_ADDON] [int] NOT NULL,
	[ISSERVICEANDMORE_ADDON] [int] NOT NULL,
	[PRINTDISCOUNTEDPIECEPRICE30010] [int] NOT NULL,
	[NVCOMMTYPESALESINVOICE] [int] NOT NULL,
	[EMAILSALESINVOICE_ADDON] [nvarchar](80) NOT NULL,
	[DIRECTDEBITMANDATE] [bigint] NOT NULL,
	[VLT_BANKFOOTER] [image] NULL,
	[VLT_INVOICEAMOUNTDISCOUNTABLE] [numeric](28, 12) NOT NULL,
	[IAXEDIINVOICELISTID] [nvarchar](20) NOT NULL,
	[IAXEDIMAILBOXNUMBER] [nvarchar](20) NOT NULL,
 CONSTRAINT [I_062RECID] PRIMARY KEY NONCLUSTERED 
(
	[DATAAREAID] ASC,
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [CUSTGROUP]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [REFNUM]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [SALESID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [ORDERACCOUNT]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVOICEACCOUNT]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [INVOICEDATE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DUEDATE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [CASHDISC]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [CASHDISCDATE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [QTY]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [VOLUME]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [WEIGHT]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [SUMLINEDISC]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [SALESBALANCE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [ENDDISC]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [INVOICEAMOUNT]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [CURRENCYCODE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [EXCHRATE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [SALESADMINISTRATOR]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVOICEID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [LEDGERVOUCHER]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [UPDATED]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DIMENSION]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DIMENSION2_]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DIMENSION3_]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [ONACCOUNTAMOUNT]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [TAXPRINTONINVOICE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [LISTCODE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [DEL_PRINTED]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DOCUMENTNUM]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DOCUMENTDATE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INTRASTATDISPATCH]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DELIVERYNAME]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DELIVERYADDRESS]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [PURCHASEORDER]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DLVTERM]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DLVMODE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [PAYMENT]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [CASHDISCCODE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [INVOICEROUNDOFF]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [SUMMARKUP]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [RETURNITEMNUM]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [POSTINGPROFILE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [BACKORDER]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DLVZIPCODE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DLVCOUNTY]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DLVCOUNTRYREGIONID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DLVSTATE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [TAXGROUP]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [TAXITEMGROUP]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [DEL_TAXSPECIFYTOTAL]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [TAXSPECIFYBYLINE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [ONETIMECUSTOMER]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [PAYMENTSCHED]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [SUMTAX]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [SALESTYPE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [PARMID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [EUSALESLIST]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [EXCHRATESECONDARY]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [TRIANGULATION]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [CUSTOMERREF]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [VATNUM]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [NUMBERSEQUENCEGROUP]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [LANGUAGEID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [INCLTAX]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [LOG]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [PAYMDAYID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVOICINGNAME]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVOICINGADDRESS]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVZIPCODE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVCOUNTY]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVCOUNTRYREGIONID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVSTATE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [GIROTYPE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [CONTACTPERSONID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [SALESORIGINID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [BILLOFLADINGID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVENTLOCATIONID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [FIXEDDUEDATE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DELIVERYCITY]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DELIVERYSTREET]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVOICECITY]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [INVOICESTREET]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [DEL_PRINTORIGINALS]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [DEL_PRINTCOPIES]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [INVOICEAMOUNTMST]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [INVOICEROUNDOFFMST]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [SUMMARKUPMST]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [SUMLINEDISCMST]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [ENDDISCMST]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [SALESBALANCEMST]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [SUMTAXMST]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [DEL_REFDLVZIPCODE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [DEL_REFINVZIPCODE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DEL_NPIBANKINGPAYMID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [NVKLZENDDISCPCT]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [NVKLZPRINTINCLTAX]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [NVAGENTACCOUNT]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [NVDESTINATIONCODEID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [DEL_CREATEDTIME]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('?') FOR [CREATEDBY]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [NVCOMPANYID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [PREPAYMENT]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [EINVOICELINESPECIFIC]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [DEL_CORRECTEDINVOICEID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT (NULL) FOR [DEL_CORRECTIVEREASON]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [EINVOICEACCOUNTCODE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [RETURNREASONCODEID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [PRINTMGMTSITEID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [RETURNSTATUS]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [PRINTEDORIGINALS]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [PROFORMA]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [REVERSECHARGE_UK]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [PAYMID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [COVSTATUS]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [NVINVOICETYPE_ADDON]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [NVPARTINVOICENUM_ADDON]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [ISSERVICEANDMORE_ADDON]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [PRINTDISCOUNTEDPIECEPRICE30010]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [NVCOMMTYPESALESINVOICE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [EMAILSALESINVOICE_ADDON]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [DIRECTDEBITMANDATE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT (NULL) FOR [VLT_BANKFOOTER]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ((0)) FOR [VLT_INVOICEAMOUNTDISCOUNTABLE]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [IAXEDIINVOICELISTID]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR] ADD  DEFAULT ('') FOR [IAXEDIMAILBOXNUMBER]
GO

ALTER TABLE [dbo].[CUSTINVOICEJOUR]  WITH NOCHECK ADD CHECK  (([RECID]<>(0)))
GO


