USE [VLT_AX500105_P_BAK]
GO

DELETE FROM [dbo].[CUSTCONFIRMSALESLINK];
DELETE FROM CUSTINVOICEJOUR;
DELETE FROM CUSTINVOICETRANS;
DELETE FROM CUSTPACKINGSLIPJOUR;
DELETE FROM CUSTPACKINGSLIPTRANS;
DELETE FROM SALESLINE;
DELETE FROM SALESTABLE;
      
GO


