USE VLT_AX500105_P


SELECT salesid, createddatetime FROM salesTable
WHERE SalesId LIKE '%430630%'
OR SalesId LIKE '%430631%'
OR SalesId LIKE '%430632%'
OR SalesId LIKE '%430633%'
OR SalesId LIKE '%430634%'
OR SalesId LIKE '%430635%'
OR SalesId LIKE '%430636%'




SELECT
	*
FROM [dbo].[INVENTTRANS]
WHERE VLT_AX500105_P.dbo.INVENTTRANS.TRANSREFID LIKE '274864/1'
	OR VLT_AX500105_P.dbo.INVENTTRANS.TRANSREFID = '274864/2'
	OR VLT_AX500105_P.dbo.INVENTTRANS.TRANSREFID = '274864/3'
	OR VLT_AX500105_P.dbo.INVENTTRANS.TRANSREFID = '393971/1'
	OR VLT_AX500105_P.dbo.INVENTTRANS.TRANSREFID = '383828/1'

SELECT
	*
FROM PRODTABLEJOUR p
WHERE p.INVENTTRANSID = '10779443'

SELECT
	*
FROM BOM b
WHERE b.BOMID = '914675'

SELECT
	*
FROM PURCHTABLE p
WHERE p.NVSALESID = '598293/1'

SELECT
	*
FROM INVENTTRANS i
WHERE NOT EXISTS (
		SELECT
			*
		FROM CUSTPACKINGSLIPJOUR AS b
		WHERE i.PACKINGSLIPID = b.PACKINGSLIPID
	)
	AND i.TRANSTYPE = 0
	AND i.STATUSISSUE > 0
	AND i.PACKINGSLIPID != ''
ORDER BY i.DATEPHYSICAL DESC;
GO

SELECT
	*
FROM INVENTTRANS i
WHERE i.INVENTTRANSID = '36287830'

SELECT
	*
FROM INVENTTRANS i
WHERE i.CUSTVENDAC = '48018'

SELECT
	*
FROM PURCHTABLE pt
WHERE pt.PURCHID = 'AV149124'

SELECT
	*
FROM SALESTABLE s
WHERE s.SALESID = '598293/1'

SELECT
	*
FROM SALESPARMTABLE s
WHERE s.SALESID = '598293/1'

SELECT
	*
FROM NVSALESCONFIRMRECEIVEDJOUR n
WHERE n.CUSTACCOUNT = '48018'

SELECT
	*
FROM NVSALESCONFIRMRECEIVEDTRANS n
WHERE n.SALESID = '598293/1'

SELECT
	*
FROM NVMONTAGETABLE n
WHERE n.SALESID = '598293/1'

SELECT
	*
FROM INVENTTRANS i

SELECT
	[DATEPHYSICAL],
	SUM([QTY])				   AS SumQty,
	[TRANSTYPE],
	[TRANSREFID]			   AS SalesId,
	[INVOICEID],
	[VOUCHER],
	[PACKINGSLIPID],
	SUM(it.COSTAMOUNTSTD)	   SumCostAmountStd,
	SUM(it.COSTAMOUNTPHYSICAL) SumCostAmountPhysical,
	SUM(it.COSTAMOUNTPOSTED)   SumCostAmountPosted,
	spt.SALESNAME,
	spt.CUSTACCOUNT
FROM [dbo].[INVENTTRANS] it
LEFT JOIN [dbo].[SALESPARMTABLE] spt ON (spt.SalesId = it.TRANSREFID)
WHERE NOT EXISTS (
		SELECT
			cpj.PACKINGSLIPID
		FROM CUSTPACKINGSLIPJOUR cpj
		WHERE it.PACKINGSLIPID = cpj.PACKINGSLIPID
	)
	AND it.PACKINGSLIPID != ''
	AND it.DATEPHYSICAL >= DATETIMEFROMPARTS(2018, 1, 1, 0, 0, 0, 0)
	AND it.DATEPHYSICAL <= DATETIMEFROMPARTS(2019, 12, 30, 0, 0, 0, 0)
	--AND it.COSTAMOUNTSTD != 0
	AND it.TRANSTYPE = 0
GROUP BY it.DATEPHYSICAL,
		 it.TRANSTYPE,
		 it.TRANSREFID,
		 it.INVOICEID,
		 it.VOUCHER,
		 it.PACKINGSLIPID,
		 spt.SALESNAME,
		 spt.CUSTACCOUNT
ORDER BY it.TRANSREFID,
		 it.DATEPHYSICAL ASC

SELECT
	MIN(i.DATEPHYSICAL)
FROM INVENTTRANS i
WHERE i.DATEPHYSICAL > DATETIMEFROMPARTS(1900, 1, 1, 0, 0, 0, 0) 


USE VLT_AX500105_D

SELECT i.ITEMID, i.LINEDISC FROM INVENTTABLEMODULE i
WHERE i.ITEMID IN ('ASM','E-MM1','E-MM2','FEI8-3D-4-IO-FS','FM8-3D-4-IO-FS','FME8-3D-4-IO-FS','FMM1-IO','FMM2-IO','G-MM1','G-MM2','IFM40Solar10','IFM40Solar6','IFM50-IO','IFM50VR-IO','IM50-K','IM78VZ','M8-FS','ME8-FS','MM1','MM2','NHK40','NHK40-AP','NHK50','NHK50-AP','NHK60','NHK60-AP','NHK80','NHK80-AP','NHK84','NHK84-AP','NM60','SET1M8','SET1M9','SET1ME8','SET1MM4','SET1MM5','SET2MM4','SET2MM5','SET3MM4','SET3MM5','SET4FME8-3D-IO','SET4FME8-IO','SET4FME9-3D-IO','SET4FME9-IO','SET4FMM4','SET4FMM4-IO','SET4FMM5','SET4FMM5-IO','SET5FME8-3DS-IO','SET5FME9-3DS-IO','SET5FME9-IO','SET5FMM4','SET5FMM4-IO','SET5FMM5','SET5FMM5-IO')
AND i.MODULETYPE = 2
AND i.DATAAREAID = '100'
ORDER BY i.ITEMID ASC
/*

