USE [VLT_AX500105_P]
GO

SELECT [DATEPHYSICAL]
      ,SUM([QTY]) AS SumQty
      ,[TRANSTYPE]
      ,[TRANSREFID] AS SalesId
      ,[INVOICEID]
      ,[VOUCHER]
      ,[PACKINGSLIPID]
      ,SUM(it.COSTAMOUNTSTD) SumCostAmountStd
	  ,SUM(it.COSTAMOUNTPHYSICAL) SumCostAmountPhysical
	  ,SUM(it.COSTAMOUNTPOSTED) SumCostAmountPosted
	  ,spt.SALESNAME
	  ,spt.CUSTACCOUNT
  FROM [dbo].[INVENTTRANS] it
  LEFT JOIN [dbo].[SALESPARMTABLE] spt ON ( spt.SALESID = it.TRANSREFID)
  WHERE NOT EXISTS (SELECT cpj.PACKINGSLIPID FROM CUSTPACKINGSLIPJOUR cpj WHERE it.PACKINGSLIPID = cpj.PACKINGSLIPID)
  AND it.PACKINGSLIPID != ''
  AND it.DATEPHYSICAL >= DATETIMEFROMPARTS(2014, 1, 1, 0, 0, 0, 0) 
  AND it.DATEPHYSICAL <= DATETIMEFROMPARTS(2017, 12, 30, 0, 0, 0, 0) 
  --AND it.COSTAMOUNTSTD != 0
  AND IT.TRANSTYPE = 0
  GROUP BY it.DATEPHYSICAL,
	it.TRANSTYPE,
	it.TRANSREFID,
	it.INVOICEID,
	it.VOUCHER,
	it.PACKINGSLIPID,
	spt.SALESNAME,
	spt.CUSTACCOUNT
ORDER BY it.TRANSREFID,
it.DATEPHYSICAL ASC
/*
  SELECT * FROM INVENTTRANS i
  WHERE i.TRANSREFID = '392541/1'

  SELECT * FROM CUSTConfirmJOUR c
  WHERE c.SALESID = '392541/1'

  SELECT * FROM CUSTCONFIRMSALESLINK c
  WHERE c.SALESID = '392541/1'
*/

GO


