USE [VLT_AX500105_T]
GO

--SELECT  pt.INVENTREFID
--  FROM [dbo].[PRODTABLE] pt
--WHERE NOT EXISTS (
--    SELECT * 
--    FROM SALESTABLE s 
--    WHERE s.SALESID = pt.INVENTREFID) 	
--AND pt.INVENTREFTYPE	= 1
----AND pt.INVENTREFID = '577196/1'
----AND pt.PRODID	= '1000270'
--ORDER BY pt.INVENTREFID DESC	
--GO


--SELECT SALESID 
--	FROM TCMSALESORDERPACKAGE sop
--WHERE NOT EXISTS (SELECT * FROM SALESTABLE s
--				WHERE s.SALESID	= sop.SALESID)

--SELECT s.QUOTATIONID, s.SALESIDREF 
--FROM SALESQUOTATIONTABLE s
----JOIN SALESTABLE s1 ON (s1.SALESID	= s.SALESIDREF)
--WHERE NOT EXISTS (SELECT SALESID FROM SALESTABLE s1
--					WHERE s.SALESIDREF = s1.SALESID)
--AND (s.SALESIDREF != '')
--ORDER BY s.SALESIDREF

--SELECT s.QUOTATIONID, s.SALESIDREF, COUNT(*) AS HavingCount
--FROM SALESQUOTATIONTABLE s
--JOIN SALESTABLE s1 ON (s1.SALESID	= s.SALESIDREF)
--GROUP BY s.SALESIDREF, s.QUOTATIONID
--HAVING COUNT(*) > 1
--ORDER BY s.SALESIDREF


--SELECT s.QUOTATIONID, s.SALESIDREF 
--FROM SALESQUOTATIONTABLE s
--WHERE s.SALESIDREF = '398233/1'

--SELECT *
--FROM salesTable s
--WHERE s.SALESID = '398233/1'


--SELECT * FROM PRODTABLE p
--WHERE p.DATAAREAID = '500'
--ORDER BY p.CREATEDDATETIME desc


--SELECT i.ITEMID,
--	   i.TRANSREFID,
--	   i.DATEPHYSICAL,
--	   i.DATEFINANCIAL
--FROM INVENTTRANS i
--WHERE i.STATUSISSUE = 1
--	AND i.TRANSTYPE = 0
--	AND NOT EXISTS (
--		SELECT SALESID
--		FROM SALESTABLE s
--		WHERE s.SALESID = i.TRANSREFID
--	)
--ORDER BY i.DATEPHYSICAL DESC


--SELECT sqt.QUOTATIONID
--FROM SALESQUOTATIONTABLE sqt
--WHERE sqt.SALESIDREF	= ''
--AND sqt.QUOTATIONSTATUS = 2
--ORDER BY sqt.CREATEDDATETIME DESC

--SELECT bomId
--FROM BOMTABLE b
--WHERE NOT EXISTS (SELECT ITEMBOMID FROM SALESLINE s
--				WHERE b.BOMID	= s.ITEMBOMID)

