USE [VLT_AX500105_P]
GO
/*
SELECT [ITEMID]
      ,[STATUSISSUE]
      ,[DATEPHYSICAL]
      ,[QTY]
      ,[COSTAMOUNTPOSTED]
      ,[CURRENCYCODE]
      ,[TRANSTYPE]
      ,[TRANSREFID]
      ,[INVOICEID]
      ,[VOUCHER]
      ,[DATEEXPECTED]
      ,[DATEFINANCIAL]
      ,[COSTAMOUNTPHYSICAL]
      ,[INVENTTRANSID]
      ,[STATUSRECEIPT]
      ,[PACKINGSLIPRETURNED]
      ,[INVOICERETURNED]
      ,[PACKINGSLIPID]
      ,[VOUCHERPHYSICAL]
      ,[COSTAMOUNTADJUSTMENT]
      ,[QTYSETTLED]
      ,[COSTAMOUNTSETTLED]
      ,[VALUEOPEN]
      ,[DIRECTION]
      ,[DATESTATUS]
      ,[COSTAMOUNTSTD]
      ,[DATECLOSED]
      ,[INVENTTRANSIDFATHER]
      ,[COSTAMOUNTOPERATIONS]
      ,[ITEMROUTEID]
      ,[ITEMBOMID]
      ,[INVENTTRANSIDRETURN]
      ,[INVENTDIMID]
      ,[INVENTDIMFIXED]
      ,[DATEINVENT]
      ,[CUSTVENDAC]
      ,[TRANSCHILDREFID]
      ,[TRANSCHILDTYPE]
      ,[REVENUEAMOUNTPHYSICAL]
      ,[TAXAMOUNTPHYSICAL]
      ,[INVENTREFTRANSID]
      ,[DATAAREAID]
      ,[RECID]
      ,[RECVERSION]
      ,[INVENTTRANSIDTRANSFER]
      ,[SHIPPINGDATEREQUESTED]
      ,[SHIPPINGDATECONFIRMED]
      ,[PICKINGROUTEID]
      ,[PROBABILITYID]
      ,[NONFINANCIALTRANSFERINVENTCL73]
      ,[ACTIVITYNUMBER]
      ,[PROJID]
      ,[PROJCATEGORYID]
      ,[ASSETID]
      ,[PROJADJUSTREFID]
      ,[ASSETBOOKID]
  FROM [dbo].[INVENTTRANS]
  WHERE VLT_AX500105_P.dbo.INVENTTRANS.TRANSREFID like '%434933%'
  --OR VLT_AX500105_P.dbo.INVENTTRANS.TRANSREFID = '274864/2'
  --OR VLT_AX500105_P.dbo.INVENTTRANS.TRANSREFID = '274864/3'
  --OR VLT_AX500105_P.dbo.INVENTTRANS.TRANSREFID = '393971/1'
  --OR VLT_AX500105_P.dbo.INVENTTRANS.TRANSREFID = '383828/1'
GO

--SELECT * FROM SALESPARMTABLE s
--WHERE s.SALESID like '%4349%'
*/

--SELECT COUNT(*) FROM DOCUREF d
--SELECT * FROM VLT_FILENAMESREF vf
SELECT COUNT(*) FROM VLT_AxFolderFiles vff
WHERE vff.AXFILENAMECOMPLETE = '\\vmvalsql01\AxDokumente\Echt\OriginalAufträge\160562.tif'


SELECT d.REFTABLEID,
d.REFRECID,
d1.ARCHIVEPATH,
d2.ORIGINALFILENAME,
d1.ARCHIVEPATH + d2.FILENAME + '.' + d2.FILETYPE AS FilenameComplete,
d.TYPEID,
d1.TYPEID,
d1.TYPEGROUP,
D.RECID
FROM DOCUREF d
JOIN DOCUTYPE d1 ON (d1.TYPEID = d.TYPEID AND d1.DATAAREAID = '100')
JOIN DOCUVALUE d2 ON (d.VALUERECID = d2.RECID)
AND d1.TYPEGROUP != 0
AND d.TYPEID NOT IN ('Adress-Dat', 'MonBA', 'WerkVertra')
AND d.REFCOMPANYID = '100'
AND d2.FILENAME ='160562'
USE VLT_AX500105_P
SELECT vff.AXFILENAMECOMPLETE
--'del ' + '"' +vff.AXFILENAMECOMPLETE + '"'
FROM VLT_AX500105_D.dbo.VLT_AXFOLDERFILES vff
WHERE vff.AXFILENAMECOMPLETE NOT IN (SELECT 
d1.ARCHIVEPATH + d2.FILENAME + '.' + d2.FILETYPE AS FilenameComplete
FROM DOCUREF d
JOIN DOCUTYPE d1 ON (d1.TYPEID = d.TYPEID AND d1.DATAAREAID = '100')
JOIN DOCUVALUE d2 ON (d.VALUERECID = d2.RECID)
AND d1.TYPEGROUP != 0
AND d.TYPEID NOT IN ('Adress-Dat', 'MonBA', 'WerkVertra')
AND d.REFCOMPANYID = '100'
AND d1.ARCHIVEPATH + d2.FILENAME + '.' + d2.FILETYPE = vff.AXFILENAMECOMPLETE)


--\\vmvalsql01\AxDokumente\Echt\OriginalAufträge\383929.tif
--\\vmvalsql01\AxDokumente\Echt\OriginalAufträge\160562.tif

ORDER BY d.REFRECID

SELECT * FROM DOCUREF 
WHERE DOCUREF.REFRECID = -2147406405

SELECT * FROM DOCUTYPE d
WHERE d.TYPEID = 'Datei'

