use VLT_AX500105_P
go

select POSTEDDATETIME,POSTEDUSERID, pt.ITEMID, pt.PRODID, pjp.QTYGOOD from prodjournaltable pjt
JOIN PRODTABLE pt on (pjt.PRODID = pt.prodId)
JOIN PRODJOURNALPROD pjp on (pjp.JOURNALID = pjt.JOURNALID)
where /*pjt.POSTEDUSERID = 'lm' 

AND*/ pjt.POSTEDDATETIME	>= DATETIMEFROMPARTS(2020, 7, 1, 0, 0, 0, 0)
AND pjt.POSTEDDATETIME <= DATETIMEFROMPARTS(2020, 7, 3, 0, 0, 0, 0) 
AND pjt.JOURNALTYPE = 1
--order by pjt.POSTEDDATETIME desc
--group by pjt.POSTEDUSERID