SELECT [INVOICEID]
      ,[INVOICEDATE]
      ,[SALESID]
      ,[ORIGSALESID]
      ,[INVOICEACCOUNT]
      ,[ORDERACCOUNT]
      ,[DELIVERYNAME]
      ,[DELIVERYADDRESS]
      ,[PARMID]
      ,[INVOICINGADDRESS]
      ,[INVOICINGNAME]
      ,[PURCHASEORDER]
      ,[CUSTOMERREF]
      ,[DATAAREAID]
      ,[RECID]
      ,[RECVERSION]
  FROM [dbo].[CUSTINVOICESALESLINK] cisl
WHERE cisl.INVOICEDATE	>= DATETIMEFROMPARTS(2014, 1, 1, 0, 0, 0, 0) AND
    cisl.INVOICEDATE <= DATETIMEFROMPARTS(2017, 4, 30, 0, 0, 0, 0)


