USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_NVMONTAGETRUPPTRANS]    Script Date: 23.07.2018 10:30:07 ******/
IF EXISTS (
		SELECT 1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_NVMONTAGETRUPPTRANS'
			AND TYPE = 'V'
	)
	DROP VIEW [dbo].[VLT_DB_POWERBI_NVMONTAGETRUPPTRANS]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_NVMONTAGETRUPPTRANS]    Script Date: 23.07.2018 10:30:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_NVMONTAGETRUPPTRANS]
AS
	SELECT mtt.MONTAGEID,
	mtt.TRUPPID,
	mtt.MONTDATE,
	mtt.HOURS,
	mtt.TURNOVERALLOCAMT,
	mtt.SALESID,
	mtt.MONTWORKTYPE,
	mtt.CALCSERVAMT,
	mtt.CALCCOSTAMT,
	mtt.MONTAGEID + mtt.DATAAREAID AS FKMontageID,
	mtt.SALESID + mtt.DATAAREAID AS FKSalesID
	FROM NVMONTAGETRUPPTRANS mtt
	WHERE mtt.DATAAREAID = '100'

GO
