USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SalesTable]    Script Date: 29.05.2018 15:52:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_CONTACTPERSON'
			AND type = 'V'
	)
	DROP VIEW [VLT_DB_POWERBI_CONTACTPERSON];
GO

CREATE VIEW [DBO].[VLT_DB_POWERBI_CONTACTPERSON]
AS
	SELECT [EMAIL],
		   [TELEX],
		   [CELLULARPHONE],
		   [PHONELOCAL],
		   [TELEFAX],
		   [URL],
		   [PHONE],
		   [STATE],
		   [COUNTY],
		   [COUNTRYREGIONID],
		   [ZIPCODE],
		   [ADDRESS],
		   [NAME],
		   [CONTACTPERSONID],
		   [TITLE],
		   [VENDACCOUNT],
		   [CUSTACCOUNT],
		   [CITY],
		   [STREET],
		   [SMS],
		   [MAINRESPONSIBLE],
		   [CONTACTPERSONPARENTID],
		   [DATAAREAID],
		   [VIP],
		   [CHARACTER],
		   [FUNCTION_],
		   [DEPARTMENT],
		   [EMAIL3],
		   [EMAIL2],
		   [PARTYID],
		   [GENDER],
		   [SUFFIX],
		   [ORGPARTYID],
		   [BIRTHDATE],
		   [FIRSTNAME],
		   [MIDDLENAME],
		   [LASTNAME],
		   CONTACTPERSON.PARTYID + CONTACTPERSON.DATAAREAID	AS FKContactPersonPartyId,
		   CONTACTPERSON.ORGPARTYID + CONTACTPERSON.DATAAREAID	AS FKContactPersonOrgPartyId
	FROM [DBO].[CONTACTPERSON]
	WHERE CONTACTPERSON.DATAAREAID = '100'

GO