USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_CUSTTRANS]    Script Date: 29.05.2018 15:52:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT
			1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_CUSTCOLLECTIONLETTERTRANS'
			AND type = 'V'
	)
	DROP VIEW [VLT_DB_POWERBI_CUSTCOLLECTIONLETTERTRANS];
GO

CREATE VIEW [DBO].[VLT_DB_POWERBI_CUSTCOLLECTIONLETTERTRANS]
AS
	SELECT
		[COLLECTIONLETTERNUM],
		[DUEDATE],
		[VOUCHER],
		[INVOICE],
		[TRANSDATE],
		[CUSTTRANSID],
		[CURRENCYCODE],
		[REMAINAMOUNT],
		[TXT],
		[CALCULATIONAMOUNT],
		[COLLECTIONLETTERISSUED],
		[DATAAREAID],
		[RECID],
		[FEE],
		[COLLECTIONLETTERCODE],
		COLLECTIONLETTERCODE.CustCollectionLetterCodeDesc,
		[NVSALESID],
		[RECVERSION],
		[ACCOUNTNUM],
		[CHECKCOMPLAINT_ADDON],
		[CHECKPARTINVOICE_ADDON],
		[CUSTCOLLECTIONINVOICETYPE30004],
		CustCollectionLetterTrans.ACCOUNTNUM + CustCollectionLetterTrans.COLLECTIONLETTERNUM + CustCollectionLetterTrans.DATAAREAID AS FKAccountNumCollectionLetterNum
	FROM [DBO].[CustCollectionLetterTrans] AS CUSTCOLLECTIONLETTERTRANS
	LEFT JOIN VLT_DB_POWERBI_CustCollectionLetterCode COLLECTIONLETTERCODE ON (COLLECTIONLETTERCODE.CustCollectionLetterCode = CUSTCOLLECTIONLETTERTRANS.COLLECTIONLETTERCODE)

GO