USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINE]    Script Date: 23.07.2018 10:30:07 ******/
IF EXISTS (
		SELECT 1
		FROM SYS.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_PRICEDISCTABLE_SALES'
			AND TYPE = 'V'
	)
	DROP VIEW [dbo].[VLT_DB_POWERBI_PRICEDISCTABLE_SALES]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINE]    Script Date: 23.07.2018 10:30:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_PRICEDISCTABLE_SALES]
AS

SELECT INVENTTABLE.[ITEMID] AS Artikelnummer,
	   INVENTTABLE.[ITEMNAME] AS Artikelname,
	   INVENTTABLE.[VLT_PIMITEMNAME] AS 'PIM - Artikelname',
	   INVENTTABLE.[ITEMGROUPID] AS Artikelgruppe,
	   INVENTTABLE.ITEMGROUPID + ' (' + INVENTITEMGROUP.NAME +')' AS Artikelgruppenname,
	   INVENTTABLE.NVBLOCKED	AS Gesperrt,	  
		PRICEDISCTABLE.ACCOUNTRELATION	AS Preisgruppe,
		PRICEDISCTABLE.FROMDATE AS 'Gültig von',
		PRICEDISCTABLE.TODATE AS 'Gültig bis',
		PRICEDISCTABLE.AMOUNT	AS 'Preis'	
FROM [dbo].[INVENTTABLE]
LEFT JOIN INVENTITEMGROUP AS INVENTITEMGROUP ON (INVENTITEMGROUP.ITEMGROUPID = INVENTTABLE.ITEMGROUPID AND INVENTITEMGROUP.DATAAREAID = INVENTTABLE.DATAAREAID)
LEFT JOIN PRICEDISCTABLE AS PRICEDISCTABLE ON (PRICEDISCTABLE.ITEMRELATION = INVENTTABLE.ITEMID AND PRICEDISCTABLE.DATAAREAID = INVENTTABLE.DATAAREAID)
	WHERE INVENTTABLE.DATAAREAID = '100'
	--AND INVENTTABLE.NVBLOCKED	= 0
	AND PRICEDISCTABLE.ACCOUNTCODE = '1'