USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINE]    Script Date: 23.07.2018 10:30:07 ******/
IF EXISTS (
		SELECT 1
		FROM SYS.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_SALESLINE'
			AND TYPE = 'V'
	)
	DROP VIEW [dbo].[VLT_DB_POWERBI_SALESLINE]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINE]    Script Date: 23.07.2018 10:30:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VLT_DB_POWERBI_SALESLINE]
AS
	SELECT SalesLine.SALESID,
		   SalesLine.SALESQTY,
		   SalesLine.LINEAMOUNT,
		   SalesLine.ITEMID,
		   SalesLine.NAME,
		   InventTable.ITEMGROUPID,
		   InventTable.ITEMTYPE,
		   InventItemGroup.NAME ItemGroupName,
		   SalesLine.SALESBOQID,
		   SalesLine.lineNum,
		   SalesLine.SALESID + SalesLine.DATAAREAID AS FKSalesTable,
		   SALESLINE.ITEMID + SalesLine.DATAAREAID AS FKInventTable,
		   InventTable.PRODPOOLID	AS PRODPOOL,
		   SalesLine.RECID	AS FKRecId,
		   DATEPART(ISO_WEEK, SalesLine.SHIPPINGDATECONFIRMED)	AS DeliveryWeek,
		   DATEPART(Year, SalesLine.SHIPPINGDATECONFIRMED)	AS DeliveryYear,
		   dbo.VLT_DB_GETDATETIMEWITHTIMEZONE(SalesLine.SHIPPINGDATECONFIRMED) AS 'Lieferdatum',
		   CONVERT(VARCHAR(10), DATEPART(YEAR, SalesLine.SHIPPINGDATECONFIRMED) * 100) + CONVERT(VARCHAR(10), DATEPART(ISO_WEEK, SalesLine.SHIPPINGDATECONFIRMED)) AS FKYearWeek
	FROM dbo.SalesLine AS SalesLine
	LEFT JOIN dbo.InventTable AS InventTable ON (SalesLine.DATAAREAID = InventTable.DATAAREAID AND SalesLine.ITEMID = InventTable.ITEMID)
	LEFT JOIN dbo.InventItemGroup AS InventItemGroup ON (InventTable.DATAAREAID = InventItemGroup.DATAAREAID AND InventTable.ITEMGROUPID = InventItemGroup.ITEMGROUPID)
	WHERE SalesLine.DATAAREAID = '100'
	AND SalesLine.CREATEDDATETIME > DATETIMEFROMPARTS(YEAR(GETDATE())-3, 1, 1, 0, 0, 0, 0)
GO


