USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINE]    Script Date: 23.07.2018 10:30:07 ******/
IF EXISTS (
		SELECT 1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_PROJECTSTATUS'
			AND type = 'V'
	)
	DROP VIEW [dbo].[VLT_DB_POWERBI_PROJECTSTATUS]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINE]    Script Date: 23.07.2018 10:30:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_PROJECTSTATUS]
AS
	SELECT st.SALESID,
		   st.NVPROJECTID,
		   st.CUSTACCOUNT,
		   st.SALESNAME,
		   sl.LINENUM,
		   sl.SALESBOQID,
		   sl.SALESQTY,
		   sl.ITEMID,
		   sl.SALESPRICE,
		   sl.LINEAMOUNT,
		   cijp.NVPARTINVOICENUM_ADDON,
		   cijp.INVOICEID,
		   cijp.INVOICEDATE,
		   cijp.INVOICEAMOUNT,
		   st.SALESID + st.DATAAREAID AS FKSalesTableSalesId,
		   sl.INVENTTRANSID + sl.DATAAREAID AS FKInventTransId,
		   cijp.SALESID + cijp.DATAAREAID AS FKCustInvoiceJourPartSalesId,
		   (
			   SELECT Value
			   FROM PBATABLEINSTANCE pWidth
			   WHERE pWidth.INVENTTRANSID = sl.INVENTTRANSID
				   AND pWidth.DATAAREAID = sl.DATAAREAID
				   AND pWidth.VARIABLE	= 'Breite'
				   AND pWidth.PBAPREPOSTVALUE	= 1
		   ) AS Breite,
		   (
			   SELECT Value
			   FROM PBATABLEINSTANCE pHeight
			   WHERE pHeight.INVENTTRANSID = sl.INVENTTRANSID
				   AND pHeight.DATAAREAID = sl.DATAAREAID
				   AND pHeight.VARIABLE	= 'Hoehe'
				   AND pHeight.PBAPREPOSTVALUE	= 1
		   ) AS Hoehe

	FROM SALESTABLE st
	JOIN SALESLINE sl ON (st.SALESID = sl.SALESID)
	LEFT JOIN CUSTINVOICEJOURPART_ADDON cijp ON (cijp.SALESID = st.SALESID AND cijp.DATAAREAID = st.DATAAREAID)
	WHERE st.MAINSALESORDER_ADDON = 1
GO