USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_PowerBI_COMMISSIONSALESREPLEAD]    Script Date: 29.05.2018 15:51:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM sys.views
		WHERE NAME = 'VLT_DB_PowerBI_COMMISSIONSALESREPLEAD'
			AND type = 'v'
	)
	DROP VIEW VLT_DB_PowerBI_COMMISSIONSALESREPLEAD;
GO

CREATE VIEW [dbo].[VLT_DB_PowerBI_COMMISSIONSALESREPLEAD]
AS
	SELECT CommSalesRep.GROUPID,
		   CommSalesRep.EMPLID,
		   CommSalesRep.NVLEADER,
		   CommSalesRep.NVUSEGROUPRIGHTS,
		   SALESGROUP.NAME AS SalesGroupNameLead,
		   SALESGROUP.VLT_SALESGROUPTERMINATED,
		   CASE
			   WHEN SALESGROUP.VLT_SALESGROUPTERMINATED = 0 THEN 'Nein'
			   WHEN SALESGROUP.VLT_SALESGROUPTERMINATED = 1 THEN 'Ja'			   
		   END 	AS 'Ausgeschieden',
		   DIRPARTYTABLE.NAME AS EmplNameLead,
		   CommSalesRep.GROUPID + ' ' + SALESGROUP.NAME AS SearchFieldGroupNameLead,
		   CommSalesRep.GROUPID + ' ' + DIRPARTYTABLE.NAME AS SearchFieldEmplNameLead,
		   CommSalesRep.EMPLID + CommSalesRep.DATAAREAID AS FKEmplID,
		   CommSalesRep.GROUPID + CommSalesRep.DATAAREAID AS FKGroupId
	FROM dbo.COMMISSIONSALESREP AS CommSalesRep
	JOIN EMPLTABLE e
	ON (e.EMPLID = CommSalesRep.EMPLID AND e.DATAAREAID = CommSalesRep.DATAAREAID)
	JOIN [dbo].[DIRPARTYTABLE] AS DirPartyTable 
	ON (e.DataAreaID = DirPartyTable.DataAreaId AND e.PartyId = DirPartyTable.PartyId)
	JOIN dbo.COMMISSIONSALESGROUP AS SALESGROUP
	ON (SALESGROUP.GROUPID = CommSalesRep.GROUPID AND SALESGROUP.DATAAREAID = CommSalesRep.DATAAREAID)
	WHERE CommSalesRep.DATAAREAID = '100'
		AND CommSalesRep.NvLeader = 1
GO

