USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_PowerBI_CommissionSalesGroup]    Script Date: 29.05.2018 15:51:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM SYS.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_COMMISSIONSALESGROUP'
			AND TYPE = 'v'
	)
	DROP VIEW VLT_DB_POWERBI_COMMISSIONSALESGROUP;
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_COMMISSIONSALESGROUP]
AS
	SELECT Salesgroup.GROUPID,
		   Salesgroup.Name,
		   Salesgroup.GROUPID + SalesGroup.DATAAREAID AS FKGroupId
	FROM dbo.COMMISSIONSALESGROUP AS Salesgroup
	WHERE Salesgroup.DATAAREAID = '100'
		AND Salesgroup.VLT_SALESGROUPTERMINATED = 0
GO

