USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_NVPROJECTQUOTE]    Script Date: 29.05.2018 15:52:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM SYS.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_NVPROJECTQUOTE'
			AND TYPE = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_NVPROJECTQUOTE;
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_NVPROJECTQUOTE]
AS
	SELECT NVPROJECTQUOTE.PROJECTID,
		   NVPROJECTQUOTE.QUOTEID,
		   NVPROJECTQUOTE.QUOTEDATE,
		   NVPROJECTQUOTE.QUOTEAMT,
		   NVPROJECTQUOTE.APPROVED,
		   NVPROJECTQUOTE.PROJECTID + NVPROJECTQUOTE.DATAAREAID AS FKProjectId
	FROM dbo.NVPROJECTQUOTE AS NVPROJECTQUOTE

	WHERE NVPROJECTQUOTE.DATAAREAID = '100'

GO

