USE [VLT_AX500105_P]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT
			1
		FROM sys.views
		WHERE NAME = 'VLT_DB_POWERBI_NVBOMDOCUPRODUCTMODEL'
			AND TYPE = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_NVBOMDOCUPRODUCTMODEL
GO

CREATE VIEW [DBO].[VLT_DB_POWERBI_NVBOMDOCUPRODUCTMODEL]
AS
	SELECT
		[PRODUCTID],
		[PBAID],
		[DATAAREAID],
		[RECID],
		[RECVERSION],
		PRODUCTID + DATAAREAID AS FKProductID
	FROM [dbo].[NVBOMDOCUPRODUCTMODEL]
GO