USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINE]    Script Date: 23.07.2018 10:30:07 ******/
IF EXISTS (
		SELECT
			1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_SALESLINE_PRODPOOL'
			AND type = 'V'
	)
	DROP VIEW [dbo].[VLT_DB_POWERBI_SALESLINE_PRODPOOL]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINE_PRODPOOL]    Script Date: 23.07.2018 10:30:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VLT_DB_POWERBI_SALESLINE_PRODPOOL]
AS
	SELECT
		SALESLINE.SALESID,
		SALESLINE.SALESQTY,
		SALESLINE.LINEAMOUNT,
		SALESLINE.ITEMID,
		SALESLINE.NAME,
		InventTable.ITEMGROUPID,
		InventTable.ITEMTYPE,
		InventItemGroup.NAME																																																									 ItemGroupName,
		SALESLINE.SALESBOQID,
		SALESLINE.LINENUM,
		SALESLINE.SALESID + SALESLINE.DATAAREAID																																																				 AS FKSalesTable,
		SALESLINE.ITEMID + SALESLINE.DATAAREAID																																																					 AS FKInventTable,
		InventTable.PRODPOOLID																																																									 AS PRODPOOL,
		SALESLINE.RECID																																																											 AS FKRecId,
		DATEPART(ISO_WEEK, SALESLINE.SHIPPINGDATECONFIRMED)																																																		 AS DeliveryWeek,
		DATEPART(YEAR, SALESLINE.SHIPPINGDATECONFIRMED)																																																			 AS DeliveryYear,
		CONVERT(DATE, dbo.VLT_DB_GETDATETIMEWITHTIMEZONE(SALESLINE.SHIPPINGDATECONFIRMED))																																										 AS 'Lieferdatum',
		InventTable.PRODPOOLID + CONVERT(VARCHAR(10), DATEPART(YEAR, dbo.VLT_DB_GETDATETIMEWITHTIMEZONE(SALESLINE.SHIPPINGDATECONFIRMED)) * 100) + CONVERT(VARCHAR(10), DATEPART(ISO_WEEK, dbo.VLT_DB_GETDATETIMEWITHTIMEZONE(SALESLINE.SHIPPINGDATECONFIRMED))) AS FKYearWeek,
		SALESTABLE.SALESTYPE,
		SalesTable.NVKLZFERTDATUM,
		CASE
		WHEN SalesTable.NVKLZFERTDATUM = '' THEN 'nicht fertig'
		WHEN SalesTable.NVKLZFERTDATUM != '' THEN 'fertig'
		END AS 'Fertiggemeldet',
		SALESTYPE.SalesTypeDesc																																																									 AS SalesTypeDesc,
		SALESTABLE.SALESSTATUS,
		SALESSTATUS.SALESSTATUSDesc																																																								 AS SALESSTATUSDesc,
		SALESTABLE.VLT_SALESORDERPRODREGSTATUS																																																					 AS ProdStatus,
		ProdRegStatus.ProdRegStatusDesc																																																							 AS ProdStatusDesc
		
	FROM dbo.SALESLINE AS SALESLINE
	JOIN SALESTABLE SALESTABLE ON (SALESTABLE.DATAAREAID = SALESLINE.DATAAREAID AND SALESTABLE.SALESID = SALESLINE.SALESID AND SALESTABLE.MAINSALESORDER_ADDON = 0)
	LEFT JOIN dbo.InventTable AS InventTable ON (SALESLINE.DATAAREAID = InventTable.DATAAREAID AND SALESLINE.ITEMID = InventTable.ITEMID)
	LEFT JOIN dbo.InventItemGroup AS InventItemGroup ON (InventTable.DATAAREAID = InventItemGroup.DATAAREAID AND InventTable.ITEMGROUPID = InventItemGroup.ITEMGROUPID)
	JOIN VLT_DB_POWERBI_SalesStatus AS SALESSTATUS ON (SALESSTATUS.SALESSTATUS = SALESLINE.SALESSTATUS)
	JOIN VLT_DB_POWERBI_SALESTYPE AS SALESTYPE ON (SALESTYPE.SALESTYPE = SALESLINE.SALESTYPE)
	JOIN [VLT_DB_POWERBI_ProdRegStatus] AS ProdRegStatus ON (ProdRegStatus.ProdRegStatus = SALESTABLE.VLT_SALESORDERPRODREGSTATUS)
	--LEFT JOIN VLT_DB_POWERBI_NvProdPoolWeek ppw ON (InventTable.PRODPOOLID = ppw.PRODPOOLID AND ppw.Weeknumber = DATEPART(ISO_WEEK, SALESLINE.SHIPPINGDATECONFIRMED) AND ppw.YearStart = DATEPART(YEAR, SALESLINE.SHIPPINGDATECONFIRMED))
	--JOIN PRODPOOL p ON (p.PRODPOOLID =  ppw.PRODPOOLID)
	WHERE SALESLINE.DATAAREAID = '100'
		AND DATEPART(YEAR, SALESLINE.SHIPPINGDATECONFIRMED) = DATEPART(YEAR, GETDATE())
		AND SALESLINE.CREATEDDATETIME > DATETIMEFROMPARTS(YEAR(GETDATE()) - 3, 1, 1, 0, 0, 0, 0)
		AND InventTable.ITEMTYPE = 1
		AND InventTable.PRODPOOLID != ''
GO


