USE [VLT_AX500105_P]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT
			1
		FROM sys.views
		WHERE NAME = 'VLT_DB_POWERBI_NVBOMDOCUPOSITIONPART'
			AND TYPE = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_NVBOMDOCUPOSITIONPART;
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_NVBOMDOCUPOSITIONPART]
AS
	SELECT
		[PRODUCTID],
		[POSITIONID],
		[PARTID],
		[LINENUM],
		[VERSIONID],
		[CHANGEREQ],
		[BLOCKED],
		[TXT],
		[CHANGETXT],
		[WIDTHADJ],
		[HEIGHTADJ],
		[DATAAREAID],
		[RECID],
		[SEARCHCOLOR],
		[SEARCHSIZE],
		[BENCHID],
		[RECVERSION],
		[QTY],
		[VALUEX],
		[VALUEY],
		[VALUEZ],
		[VLT_EXPLOREBOM],
		PRODUCTID + DATAAREAID AS FKProductID,
		VERSIONID + PRODUCTID + DATAAREAID AS FKVersionProductID,
		POSITIONID + VERSIONID + PRODUCTID + DATAAREAID AS FKPositionVersionProductID,
		PARTID + POSITIONID + VERSIONID + PRODUCTID + DATAAREAID AS FKPartPositionVersionProductID
	FROM [dbo].[NVBOMDOCUPOSITIONPART]
GO