USE [VLT_AX500105_P]
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT
			1
		FROM sys.views
		WHERE NAME = 'VLT_DB_POWERBI_NVBOMDOCUVERSION'
			AND TYPE = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_NVBOMDOCUVERSION;
GO

CREATE VIEW [DBO].[VLT_DB_POWERBI_NVBOMDOCUVERSION]
AS
	SELECT
		[PRODUCTID],
		[VERSIONID],
		[NAME],
		[TXT],
		[ACTIVE],
		[CHANGEREQ],
		[CHANGETXT],
		[DATAAREAID],
		[RECID],
		[RECVERSION],
		PRODUCTID + DATAAREAID AS FKProductID,
		VERSIONID + PRODUCTID + DATAAREAID AS FKVersionProductID
	FROM [DBO].[NVBOMDOCUVERSION]
GO