USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINEMAINORDERSALESBQ]    Script Date: 08.11.2018 10:44:08 ******/
IF EXISTS (
		SELECT 1
		FROM SYS.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_SALESLINEMAINORDERSALESBQ'
			AND TYPE = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_SALESLINEMAINORDERSALESBQ;
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINEMAINORDERSALESBQ]    Script Date: 08.11.2018 10:44:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VLT_DB_POWERBI_SALESLINEMAINORDERSALESBQ]
AS
	SELECT NvProjectTable.PROJECTID,
		   MainSalesTable.SALESID,
		   MainSalesLine.LINENUM,
		   MainSalesLine.SALESBOQID,
		   MainSalesLine.SALESQTY,
		   MainSalesLine.LineAmount,
		   NvProjectTable.PROJECTID + NvProjectTable.DATAAREAID AS FKProjectId
	FROM dbo.NVPROJECTTABLE AS NvProjectTable
	JOIN dbo.SALESTABLE AS MainSalesTable ON (MainSalesTable.NVPROJECTID = NvProjectTable.PROJECTID AND MainSalesTable.MAINSALESORDER_ADDON = 1)
	JOIN SALESLINE AS MainSalesLine ON (MainSalesLine.SALESID = MainSalesTable.SALESID AND MainSalesLine.SALESQTY > 0 AND MainSalesLine.SALESBOQID != '' AND MainSalesLine.SALESBOQID IS NOT NULL)
	WHERE NvProjectTable.DATAAREAID = '100'
--AND NvProjectTable.PROJECTID = '009690'

GO


