USE [VLT_AX500105_P]
GO
/****** Object:  View [dbo].[VLT_DB_POWERBI_CUSTTRANS]    Script Date: 29.05.2018 15:52:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM SYS.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_CUSTTRANSOPEN'
			AND TYPE = 'V'
	)
	DROP VIEW [VLT_DB_POWERBI_CUSTTRANSOPEN];
GO

CREATE VIEW [DBO].[VLT_DB_POWERBI_CUSTTRANSOPEN]
AS
	SELECT CUSTTRANSOPEN.AMOUNTCUR,
	CUSTTRANSOPEN.AMOUNTMST,
	CUSTTRANSOPEN.DUEDATE,
	CUSTTRANSOPEN.REFRECID,
	CUSTTRANSOPEN.CASHDISCDATE,
	CUSTTRANSOPEN.TRANSDATE,
	CUSTTRANSOPEN.POSSIBLECASHDISC,
	CUSTTRANSOPEN.ACCOUNTNUM,
	CUSTTRANSOPEN.USECASHDISC,
	CUSTTRANSOPEN.LASTINTERESTDATE,
	CUSTTRANSOPEN.BANKDISCNOTICEDEADLINE,
	CUSTTRANSOPEN.CASHDISCACCOUNT,
	CUSTTRANSOPEN.EXCHADJUNREALIZED,
	CUSTTRANSOPEN.ACCOUNTNUM + CUSTTRANSOPEN.DATAAREAID AS FKAccountNum,
	CUSTTRANSOPEN.ACCOUNTNUM + CUSTTRANSOPEN.REFRECID + CUSTTRANSOPEN.DATAAREAID AS FKAccountNumRefRecId
	FROM dbo.CUSTTRANSOPEN AS CustTransOpen
	WHERE CUSTTRANSOPEN.DATAAREAID = '100'
	AND CUSTTRANSOPEN.TRANSDATE > DATETIMEFROMPARTS(YEAR(GETDATE())-3, 3, 1, 0, 0, 0, 0)
GO