USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_SALESLINEMAINORDER]    Script Date: 29.05.2018 15:52:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM SYS.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_SALESLINEMAINORDER'
			AND TYPE = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_SALESLINEMAINORDER;
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_SALESLINEMAINORDER]
AS
	SELECT NvProjectTable.PROJECTID,
		   MainSalesTable.SALESID,
		   MainSalesLine.LINENUM,
		   MainSalesLine.SALESBOQID,
		   MainSalesLine.SALESQTY,
		   MainSalesLine.LineAmount,
		   NvProjectTable.PROJECTID + NvProjectTable.DATAAREAID AS FKProjectId,
		   MainSalesLine.SALESID + mainSalesLine.DATAAREAID AS FKMainSalesId
	FROM dbo.NVPROJECTTABLE AS NvProjectTable
	JOIN dbo.SALESTABLE AS MainSalesTable ON (MainSalesTable.NVPROJECTID = NvProjectTable.PROJECTID AND MainSalesTable.MAINSALESORDER_ADDON = 1)
	JOIN SALESLINE AS MainSalesLine ON (MainSalesLine.SALESID = MainSalesTable.SALESID AND MainSalesLine.SALESQTY > 0)
	WHERE NvProjectTable.DATAAREAID = '100'
--AND NvProjectTable.PROJECTID = '009690'

GO

