USE [VLT_AX500105_P]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT
			1
		FROM sys.views
		WHERE NAME = 'VLT_DB_POWERBI_CustPackingSlipProject'
			AND TYPE = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_CustPackingSlipProject;
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_CustPackingSlipProject]
AS
SELECT
	st.NVPROJECTID		AS Projekt,
	cpj.SALESID			 AS AUFTRAG,
	cpj.PACKINGSLIPID	 AS Lieferschein,
	cpj.INVOICEACCOUNT	 AS Debitornummer,
	cpj.INVOICINGNAME	 AS Debitor,
	cpj.INVOICINGADDRESS AS Adresse,
	cpt.ITEMID			AS Artikel,
	cpt.SalesBOQId_Addon	AS LVZ,
	FORMAT(cpt.QTY, 'N2')	AS Menge,
	cpt.SALESUNIT	AS Einheit,
	cpt.DELIVERYDATE	As Lieferdatum,
	pti.VALUE	AS Fensterpos,
	cpt.INVENTTRANSID
FROM CUSTPACKINGSLIPJOUR cpj
JOIN SALESTABLE st ON (cpj.SALESID = st.SALESID)
JOIN CUSTPACKINGSLIPTRANS cpt ON (cpj.PACKINGSLIPID = cpt.PACKINGSLIPID AND cpj.SALESID = cpt.SALESID AND cpj.DELIVERYDATE = cpt.DELIVERYDATE)
LEFT JOIN PBATABLEINSTANCE pti ON (pti.INVENTTRANSID = cpt.inventtransid)
LEFT JOIN SALESLINE sl	ON (sl.INVENTTRANSID	= cpt.INVENTTRANSID)
WHERE cpj.DATAAREAID = '100'
AND st.NVPROJECTID != ''
AND pti.VARIABLE = 'Fensterpos'
AND pti.PBAPREPOSTVALUE	= 1
AND pti.DATAAREAID = '100'
GO