USE [VLT_AX500105_P]
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT
			1
		FROM sys.views
		WHERE NAME = 'VLT_DB_POWERBI_NVBOMDOCUPRODUCTTABLE'
			AND TYPE = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_NVBOMDOCUPRODUCTTABLE;
GO

CREATE VIEW [DBO].[VLT_DB_POWERBI_NVBOMDOCUPRODUCTTABLE]
AS
	SELECT
		[PRODUCTID],
		[NAME],
		[DATAAREAID],
		[RECID],
		[RECVERSION],
		[TESTVERSIONID],
		[TESTER1],
		[TESTER2],
		[TESTER3],
		PRODUCTID + DATAAREAID AS FKProductID
	FROM [DBO].[NVBOMDOCUPRODUCTTABLE]
GO