USE [VLT_AX500105_P]
GO


IF EXISTS (
		SELECT 1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_INVENTITEMGROUP'
			AND type = 'V'
	)
	DROP VIEW [dbo].[VLT_DB_POWERBI_INVENTITEMGROUP]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VLT_DB_POWERBI_INVENTITEMGROUP]
AS
	SELECT INVENTITEMGROUP.ITEMGROUPID,
	INVENTITEMGROUP.NAME,
	INVENTITEMGROUP.ITEMGROUPID + ' (' + INVENTITEMGROUP.NAME +')' AS Artikelgruppe,
	INVENTITEMGROUP.ITEMGROUPID + INVENTITEMGROUP.DATAAREAID AS PKINVENTITEMGROUP
	FROM dbo.INVENTITEMGROUP AS INVENTITEMGROUP	
	WHERE INVENTITEMGROUP.DATAAREAID = '100'
GO


