USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_PowerBI_EmplTable]    Script Date: 29.05.2018 15:51:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT
			1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_SALESTYPE'
			AND type = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_SALESTYPE;
GO


CREATE VIEW [dbo].[VLT_DB_POWERBI_SALESTYPE]
AS
	SELECT
		0	   AS SALESTYPE,
		'Journal' AS SALESTYPEDesc
	UNION
	SELECT
		1				  AS SALESTYPE,
		'Angebot' AS SALESTYPEDesc
	UNION
	SELECT
		2			AS SALESTYPE,
		'Dauerauftrag' AS SALESTYPEDesc
	UNION
	SELECT
		3			 AS SALESTYPE,
		'Auftrag' AS SALESTYPEDesc
	UNION
	SELECT
		4			AS SALESTYPE,
		'Zurückgegebener' AS SalesTypeDesc
	UNION
	SELECT
		5			AS SALESTYPE,
		'Abruf' AS SalesTypeDesc
	UNION
	SELECT
		6			AS SALESTYPE,
		'Artikelbedarf' AS SALESTYPEDesc
GO


