USE [VLT_AX500105_P]
GO


IF EXISTS (
		SELECT 1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_INVENTTABLE'
			AND type = 'V'
	)
	DROP VIEW [dbo].[VLT_DB_POWERBI_INVENTTABLE]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VLT_DB_POWERBI_INVENTTABLE]
AS
	SELECT INVENTTABLE.ITEMID,
		   INVENTTABLE.ITEMGROUPID,
		   INVENTTABLE.ITEMGROUPID + ' (' + INVENTITEMGROUP.NAME +')' AS Artikelgruppe,
		   INVENTTABLE.ITEMID + INVENTTABLE.DATAAREAID AS FKInventTableTable,
		   INVENTTABLE.ITEMGROUPID + + INVENTTABLE.DATAAREAID AS FKInventTableItemGroup
	FROM dbo.INVENTTABLE AS INVENTTABLE
	LEFT JOIN INVENTITEMGROUP AS INVENTITEMGROUP ON (INVENTITEMGROUP.ITEMGROUPID = INVENTTABLE.ITEMGROUPID AND INVENTITEMGROUP.DATAAREAID = INVENTTABLE.DATAAREAID)
	WHERE INVENTTABLE.DATAAREAID = '100'
GO


