USE [VLT_AX500105_P]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT
			1
		FROM sys.views
		WHERE NAME = 'VLT_DB_POWERBI_BATCHJOBHISTORY'
			AND type = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_BATCHJOBHISTORY;
GO

CREATE VIEW [dbo].VLT_DB_POWERBI_BATCHJOBHISTORY
AS
	SELECT
		[STATUS],
		bs.BATCHSTATUSDesc,
		[FINISHING],
		[CAPTION],
		[BATCHJOBID],
		[STARTDATETIME],
		CONVERT(DATE, [STARTDATETIME])						  AS 'STARTDATE',
		dbo.VLT_DB_GETDATETIMEWITHTIMEZONE(STARTDATETIME)	  AS 'STARTDATETIMETZ',
		[STARTDATETIMETZID],
		[ENDDATETIME],
		CONVERT(DATE, [ENDDATETIME])						  AS 'ENDDATE',
		dbo.VLT_DB_GETDATETIMEWITHTIMEZONE([ENDDATETIME])	  AS 'EndDateTimeTZ',
		[ENDDATETIMETZID],
		[ORIGSTARTDATETIME],
		CONVERT(DATE, [ORIGSTARTDATETIME])					  AS 'ORIGSTARTDATE',
		dbo.VLT_DB_GETDATETIMEWITHTIMEZONE(ORIGSTARTDATETIME) AS 'ORIGSTARTDATETIMETZ',
		[ORIGSTARTDATETIMETZID],
		[COMPANY],
		[ALERTSPROCESSED],
		[BATCHCREATEDBY],
		[CANCELEDBY],
		[CREATEDDATETIME],
		CONVERT(DATE, [CREATEDDATETIME])					  AS 'CREATEDDATE',
		dbo.VLT_DB_GETDATETIMEWITHTIMEZONE([CREATEDDATETIME]) AS 'CREATEDDATETIMETZ',
		[RECVERSION],
		[RECID]
	FROM [dbo].[BATCHJOBHISTORY]
	JOIN VLT_DB_POWERBI_BatchStatus bs ON bs.BATCHSTATUS = Batchjobhistory.status
	WHERE DATEPART(YEAR, STARTDATETIME) = DATEPART(YEAR, GETDATE())
	
GO

