USE [VLT_AX500105_P]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT
			1
		FROM sys.views
		WHERE NAME = 'VLT_DB_POWERBI_TCMMainSalesOrderCapacity'
			AND type = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_TCMMainSalesOrderCapacity;
GO

CREATE VIEW [dbo].VLT_DB_POWERBI_TCMMainSalesOrderCapacity
AS

	SELECT	 msoc.PRODPOOLID,
	SUM(msoc.SALESQTY) AS QtyMainOrder,
    DATEPART(WEEK, msoc.WEEKSTARTING)	 AS WeekPlanned
	FROM TCMMAINSALESORDERCAPACITY msoc
	WHERE msoc.DATAAREAID = '100'
	AND DATEPART(YEAR, msoc.WEEKSTARTING) = DATEPART(YEAR, GETDATE())
	GROUP BY msoc.PRODPOOLID, DATEPART(WEEK, msoc.WEEKSTARTING)
GO

