USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_PROVISIONINVOICED]    Script Date: 29.05.2018 15:52:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_PROVISIONEXPECTED'
			AND type = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_PROVISIONEXPECTED;
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_PROVISIONEXPECTED]
AS
	SELECT ProjectTable.PROJECTID,
		   ProjectTable.PROJECTNAME,
		   SalesTableMain.SALESID,
		   SalesTableMain.SALESNAME,
		   SalesTableMain.CUSTOMERREF,
		   ProjectTable.CONTRACTDATE,
		   ProjectTable.FIXEDENDDATE,
		   ProjectTable.PROJECTMANAGERID AS PL,
		   ProjectTable.VLT_COMMISSSALESGROUPPROJ30102 AS CommissionGroupPL,
		   ComCalcPL.COMMISSIONBASE AS CommissionBasePL,
		   /*CASE
	  			WHEN (SalesTableMain.SALESID = '' AND SalesTableMain.COMMISSIONGROUP = '' AND ProjectTable.VLT_COMMISSSALESGROUPPROJ30102 = '') THEN 1
	  			WHEN (SalesTableMain.SALESID IS NULL AND SalesTableMain.COMMISSIONGROUP IS NULL AND (ProjectTable.VLT_COMMISSSALESGROUPPROJ30102 IS NULL)) THEN 1
	  		ELSE ProjectTable.VLT_COMMISSSALESGROUPPROJ30102
	  		END AS CommissionGroupPL,*/
		   ProjectTable.TCMTECHNICALMANAGERID AS TB,
		   ProjectTable.VLT_COMMISSSALESGROUPTECH30103 AS CommissionGroupTB,
		   ComCalcTB.COMMISSIONBASE AS CommissionBaseTB,
		   /*CASE
	  			WHEN (SalesTableMain.SALESID = '' AND ProjectTable.VLT_COMMISSSALESGROUPTECH30103 = '') THEN 1
	  			WHEN (SalesTableMain.SALESID IS NULL AND ProjectTable.VLT_COMMISSSALESGROUPTECH30103 IS NULL) THEN 1
	  		ELSE ProjectTable.VLT_COMMISSSALESGROUPTECH30103
	  		END AS CommissionGroupTB,*/
		   SalesTableMain.SALESGROUP,
		   SalesTableMain.COMMISSIONGROUP,
		   CASE
			   WHEN SalesTableMain.SALESID = '' THEN 0
			   WHEN SalesTableMain.SALESID IS NULL THEN 0
			   ELSE ComCalcOne.COMMISSIONBASE
		   END AS ComBaseGroupOne,
		   ComCalcOne.COMMISSIONBASE AS CommissionBaseOne,
		   SalesTableMain.NVSALESGROUP2,
		   SalesTableMain.NVCOMMISSIONGROUP2,
		   CASE
			   WHEN SalesTableMain.SALESID = '' THEN 0
			   WHEN SalesTableMain.SALESID IS NULL THEN 0
			   ELSE ComCalcTwo.COMMISSIONBASE
		   END AS ComBaseGroupTwo,
		   ComCalcTwo.COMMISSIONBASE AS CommissionBaseTwo,
		   ProjectTable.Price,
		   (
			   SELECT SUM(LineAmount)
			   FROM SALESLINE
			   WHERE SALESLINE.SALESID = SalesTableMain.SALESID
		   ) AS SalesLineAmount,
		   (
			   SELECT SUM(NVPROJECTQUOTE.QUOTEAMT)
			   FROM NVPROJECTQUOTE
			   WHERE NVPROJECTQUOTE.DATAAREAID = ProjectTable.DATAAREAID
				   AND NVPROJECTQUOTE.PROJECTID = ProjectTable.PROJECTID
				   AND NVPROJECTQUOTE.APPROVED = 1
			   GROUP BY NVPROJECTQUOTE.ProjectId
		   ) AS QuoteAmount,
		   CASE
			   WHEN (
					   SELECT SUM(NVPROJECTQUOTE.QUOTEAMT)
					   FROM NVPROJECTQUOTE
					   WHERE NVPROJECTQUOTE.DATAAREAID = ProjectTable.DATAAREAID
						   AND NVPROJECTQUOTE.PROJECTID = ProjectTable.PROJECTID
						   AND NVPROJECTQUOTE.APPROVED = 1
					   GROUP BY NVPROJECTQUOTE.ProjectId
				   ) IS NULL THEN ProjectTable.Price
			   ELSE (
					   SELECT SUM(NVPROJECTQUOTE.QUOTEAMT)
					   FROM NVPROJECTQUOTE
					   WHERE NVPROJECTQUOTE.DATAAREAID = ProjectTable.DATAAREAID
						   AND NVPROJECTQUOTE.PROJECTID = ProjectTable.PROJECTID
						   AND NVPROJECTQUOTE.APPROVED = 1
					   GROUP BY NVPROJECTQUOTE.ProjectId
				   ) + ProjectTable.PRICE
		   END AS QuoteAmountApproved,
		   1.0 AS ComBaseStdOne,
		   1.0 AS ComBaseStdTwo,
		   ProjectTable.PROJECTID + ProjectTable.DATAAREAID AS FKProjectID,
		   --CommSalesGroup.GroupId + SalesTableMain.DATAAREAID	AS FKSalesGroupAll,	
		   SalesTableMain.SALESGROUP + SalesTableMain.DATAAREAID AS FKSalesGroup,
		   SalesTableMain.NVSALESGROUP2 + SalesTableMain.DATAAREAID AS FKNvSalesGroup2,
		   SalesTableMain.SALESID + SalesTableMain.DATAAREAID AS FKMainSalesId,
		   ProjectTable.TCMTECHNICALMANAGERID + ProjectTable.DATAAREAID AS FKTechnicalManager,
		   ProjectTable.PROJECTMANAGERID + ProjectTable.DATAAREAID AS FKProjectManager
	FROM NVPROJECTTABLE AS ProjectTable
	LEFT JOIN SALESTABLE AS SalesTableMain ON (SalesTableMain.NVPROJECTID = ProjectTable.PROJECTID AND SalesTableMain.MAINSALESORDER_ADDON = 1 AND SalesTableMain.SALESSTATUS < 3)
	LEFT JOIN dbo.COMMISSIONCUSTOMERGROUP AS ComCustGroupOne ON (ComCustGroupOne.DATAAREAID = SalesTableMain.DATAAREAID AND ComCustGroupOne.GROUPID = SalesTableMain.COMMISSIONGROUP)
	LEFT JOIN COMMISSIONCALC AS ComCalcOne ON (ComCalcOne.DATAAREAID = ComCustGroupOne.DATAAREAID AND ComCalcOne.CUSTOMERRELATION = ComCustGroupOne.GROUPID AND ComCalcOne.CUSTOMERCODE = 1)
	LEFT JOIN dbo.COMMISSIONCUSTOMERGROUP AS ComCustGroupTwo ON (ComCustGroupTwo.DATAAREAID = SalesTableMain.DATAAREAID AND ComCustGroupTwo.GROUPID = SalesTableMain.NVCOMMISSIONGROUP2)
	LEFT JOIN COMMISSIONCALC AS ComCalcTwo ON (ComCalcTwo.DATAAREAID = ComCustGroupTwo.DATAAREAID AND ComCalcTwo.CUSTOMERRELATION = ComCustGroupTwo.GROUPID)
	LEFT JOIN dbo.COMMISSIONCUSTOMERGROUP AS ComCustGroupPL ON (ComCustGroupPL.DATAAREAID = ProjectTable.DATAAREAID AND ComCustGroupPL.GROUPID = ProjectTable.VLT_COMMISSSALESGROUPPROJ30102)
	LEFT JOIN COMMISSIONCALC AS ComCalcPL ON (ComCalcPL.DATAAREAID = ComCustGroupPL.DATAAREAID AND ComCalcPL.CUSTOMERRELATION = ComCustGroupPL.GROUPID AND ComCalcPL.CUSTOMERCODE = 1)
	LEFT JOIN dbo.COMMISSIONCUSTOMERGROUP AS ComCustGroupTB ON (ComCustGroupTB.DATAAREAID = ProjectTable.DATAAREAID AND ComCustGroupTB.GROUPID = ProjectTable.VLT_COMMISSSALESGROUPTECH30103)
	LEFT JOIN COMMISSIONCALC AS ComCalcTB ON (ComCalcTB.DATAAREAID = ComCustGroupTB.DATAAREAID AND ComCalcTB.CUSTOMERRELATION = ComCustGroupTB.GROUPID AND ComCalcTB.CUSTOMERCODE = 1)
	/*LEFT Join COMMISSIONSALESGROUP	AS CommSalesGroup
			ON (CommSalesGroup.DATAAREAID	= SalesTableMain.DATAAREAID
				AND (CommSalesGroup.GROUPID = SalesTableMain.SALESGROUP 
				OR CommSalesGroup.GROUPID	= SalesTableMain.NVSALESGROUP2
				OR SalesTableMain.NVSALESGROUP2 is Null))*/
	WHERE ProjectTable.DATAAREAID = '100'
		AND ProjectTable.PROJECTSTATE = 0


GO

