USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_PowerBI_COMMISSIONSALESREPSUB]    Script Date: 29.05.2018 15:51:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM sys.views
		WHERE NAME = 'VLT_DB_PowerBI_COMMISSIONSALESREPSUB'
			AND type = 'v'
	)
	DROP VIEW VLT_DB_PowerBI_COMMISSIONSALESREPSUB;
GO

CREATE VIEW [dbo].[VLT_DB_PowerBI_COMMISSIONSALESREPSUB]
AS
	SELECT CommSalesRep.GROUPID,
		   CommSalesRep.EMPLID AS EMPLIDSUB,
		   CommSalesRep.NVLEADER AS NVLeaderSub,
		   CommSalesRep.NVUSEGROUPRIGHTS AS NvUserGroupRightsSub,
		   SALESGROUP.NAME AS SalesGroupNameLead,
		   SALESGROUP.VLT_SALESGROUPTERMINATED AS SalesGroupTerminatedLead,
		   CASE
			   WHEN SALESGROUP.VLT_SALESGROUPTERMINATED = 0 THEN 'Nein'
			   WHEN SALESGROUP.VLT_SALESGROUPTERMINATED = 1 THEN 'Ja'			   
		   END 	AS 'Ausgeschieden (Leiter)',
		   SALESGROUPSUB.VLT_SALESGROUPTERMINATED AS SalesGroupTerminatedSub,
		   CASE
			   WHEN SALESGROUPSUB.VLT_SALESGROUPTERMINATED = 0 THEN 'Nein'
			   WHEN SALESGROUPSUB.VLT_SALESGROUPTERMINATED = 1 THEN 'Ja'			   
		   END 	AS 'Ausgeschieden',
		   DIRPARTYTABLE.NAME AS EmplNameSub,
		   CommSalesRepSub.GROUPID	AS SalesGroupIdSUB,
		   CommSalesRepSub.GROUPID + ' ' + SALESGROUP.NAME AS SearchFieldGroupNameSub,
		   CommSalesRepSub.GROUPID + ' ' + DIRPARTYTABLE.NAME AS SearchFieldEmplNameSub,
		   CommSalesRep.EMPLID + CommSalesRep.DATAAREAID AS FKEmplID,
		   CommSalesRep.GROUPID + CommSalesRep.DATAAREAID AS FKGroupId,
		   CommSalesRepSub.GROUPID + CommSalesRep.DATAAREAID AS FKGroupIdSUB
	FROM dbo.COMMISSIONSALESREP AS CommSalesRep
	JOIN EMPLTABLE e
	ON (e.EMPLID = CommSalesRep.EMPLID AND e.DATAAREAID = CommSalesRep.DATAAREAID)
	JOIN [dbo].[DIRPARTYTABLE] AS DirPartyTable 
	ON (e.DataAreaID = DirPartyTable.DataAreaId AND e.PartyId = DirPartyTable.PartyId)
	JOIN dbo.COMMISSIONSALESGROUP AS SALESGROUP
	ON (SALESGROUP.GROUPID = CommSalesRep.GROUPID AND SALESGROUP.DATAAREAID = CommSalesRep.DATAAREAID)
	JOIN dbo.COMMISSIONSALESREP CommSalesRepSub
	ON (CommSalesRepSub.EMPLID = CommSalesRep.EMPLID AND CommSalesRepSub.DATAAREAID = CommSalesRep.DATAAREAID)
	JOIN dbo.COMMISSIONSALESGROUP AS SALESGROUPSUB
	ON (SALESGROUPSUB.GROUPID = CommSalesRepSub.GROUPID AND SALESGROUP.DATAAREAID = CommSalesRepSub.DATAAREAID)
	WHERE CommSalesRep.DATAAREAID = '100'
		AND CommSalesRep.NvLeader = 0
GO

