USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_PowerBI_SalesLine]    Script Date: 29.05.2018 15:52:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM SYS.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_SALESLINESUM'
			AND TYPE = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_SALESLINESUM;
GO

CREATE VIEW [DBO].[VLT_DB_POWERBI_SALESLINESUM]
AS
	SELECT SalesLine.SALESID,
		   SUM(SalesLine.SALESQTY) AS SUMQty,
		   SUM(SalesLine.LINEAMOUNT) AS SUMLineAmount,
		   SalesLine.ITEMID,
		   SalesLine.SALESID + SalesLine.DATAAREAID AS FKSalesTable
	FROM dbo.SalesLine AS SalesLine
	WHERE SalesLine.DATAAREAID = '100'
	GROUP BY SalesLine.SALESID,
			 SalesLine.ITEMID,
			 SalesLine.DATAAREAID
GO

