USE [VLT_AX500105_P]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT
			1
		FROM sys.views
		WHERE NAME = 'VLT_DB_POWERBI_BATCHJOB'
			AND type = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_BATCHJOB;
GO

CREATE VIEW [dbo].VLT_DB_POWERBI_BATCHJOB
AS
	SELECT
		[FINISHING],
		[STATUS],
		[RECURRENCEDATA],
		[CAPTION],
		[COMPANY],
		[CANCELEDBY],
		[LOGLEVEL],
		[ORIGSTARTDATETIME],
		CONVERT(DATE, [ORIGSTARTDATETIME])					  AS 'ORIGSTARTDATE',
		dbo.VLT_DB_GETDATETIMEWITHTIMEZONE(ORIGSTARTDATETIME) AS 'ORIGSTARTDATETIMETZ',
		[ORIGSTARTDATETIMETZID],
		[STARTDATETIME],
		CONVERT(DATE, [STARTDATETIME])						  AS 'STARTDATE',
		dbo.VLT_DB_GETDATETIMEWITHTIMEZONE(STARTDATETIME)	  AS 'STARTDATETIMETZ',
		[STARTDATETIMETZID],
		[ENDDATETIME],
		CONVERT(DATE, [ENDDATETIME])						  AS 'ENDDATE',
		dbo.VLT_DB_GETDATETIMEWITHTIMEZONE([ENDDATETIME])	  AS 'EndDateTimeTZ',
		[ENDDATETIMETZID],
		[CREATEDDATETIME],
		CONVERT(DATE, [CREATEDDATETIME])					  AS 'CREATEDDATE',
		dbo.VLT_DB_GETDATETIMEWITHTIMEZONE([CREATEDDATETIME]) AS 'CREATEDDATETIMETZ',
		[CREATEDBY],
		[RECVERSION],
		[RECID]
	FROM [dbo].[BATCHJOB]
GO

