USE [VLT_AX500105_P]
GO

/****** Object:  View [dbo].[VLT_DB_POWERBI_NVPROJECTTABLE]    Script Date: 29.05.2018 15:52:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_NVPROJECTTABLE'
			AND type = 'V'
	)
	DROP VIEW VLT_DB_POWERBI_NVPROJECTTABLE;
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_NVPROJECTTABLE]
AS
	SELECT NvProjectTable.PROJECTID,
		   NvProjectTable.STATUSID,
		   NvProjectTable.PROJECTMANAGERID,
		   EmplTableProjectManager.NAME AS ProjectManagerName,
		   NvProjectTable.TCMTECHNICALMANAGERID,
		   EmplTableTechnicalManager.NAME AS TechnicalManagerName,
		   NvProjectTable.CONTRACTDATE,
		   NvProjectTable.FIXEDENDDATE,
		   NvProjectTable.CLIENTNAME,
		   NvProjectTable.PROJECTNAME,
		   NvProjectTable.PRICE,
		   NvProjectTable.TCMMAINSALESORDERAMOUNT,
		   (
			   SELECT TOP 1 (INVOICEAMOUNT - SUMTAX)
			   FROM CUSTINVOICEJOURPART_ADDON
			   JOIN SALESTABLE ON (SALESTABLE.SALESID = VLT_AX500105_P.dbo.CUSTINVOICEJOURPART_ADDON.SALESID AND SALESTABLE.NVPROJECTID = NvProjectTable.PROJECTID AND SALESTABLE.MAINSALESORDER_ADDON = 1)
			   ORDER BY CUSTINVOICEJOURPART_ADDON.INVOICEDATE DESC
		   ) AS SumPartInvoice,
		   (
			   SELECT SUM(NVPROJECTQUOTE.QUOTEAMT)
			   FROM NVPROJECTQUOTE
			   WHERE NVPROJECTQUOTE.DATAAREAID = NvProjectTable.DATAAREAID
				   AND NVPROJECTQUOTE.PROJECTID = NvProjectTable.PROJECTID
				   AND NVPROJECTQUOTE.APPROVED = 1
			   GROUP BY NVPROJECTQUOTE.PROJECTID
		   ) AS QuoteAmount,

		   CASE
			   WHEN (
					   SELECT SUM(NVPROJECTQUOTE.QUOTEAMT)
					   FROM NVPROJECTQUOTE
					   WHERE NVPROJECTQUOTE.DATAAREAID = NvProjectTable.DATAAREAID
						   AND NVPROJECTQUOTE.PROJECTID = NvProjectTable.PROJECTID
						   AND NVPROJECTQUOTE.APPROVED = 1
					   GROUP BY NVPROJECTQUOTE.PROJECTID
				   ) IS NULL THEN NvProjectTable.PRICE
			   ELSE (
					   SELECT SUM(NVPROJECTQUOTE.QUOTEAMT)
					   FROM NVPROJECTQUOTE
					   WHERE NVPROJECTQUOTE.DATAAREAID = NvProjectTable.DATAAREAID
						   AND NVPROJECTQUOTE.PROJECTID = NvProjectTable.PROJECTID
						   AND NVPROJECTQUOTE.APPROVED = 1
					   GROUP BY NVPROJECTQUOTE.PROJECTID
				   ) + NvProjectTable.PRICE
		   END AS QuoteAmountApproved,
		   NvProjectTable.PROJECTID + NvProjectTable.DATAAREAID AS FKProjectId
	FROM dbo.NvProjectTable AS NvProjectTable
	LEFT JOIN dbo.[VLT_DB_POWERBI_EMPLTABLE] AS EmplTableProjectManager ON (EmplTableProjectManager.EMPLID = NvProjectTable.PROJECTMANAGERID)
	LEFT JOIN dbo.[VLT_DB_POWERBI_EMPLTABLE] AS EmplTableTechnicalManager ON (EmplTableTechnicalManager.EMPLID = NvProjectTable.TCMTECHNICALMANAGERID)
	WHERE NvProjectTable.DATAAREAID = '100'
		AND NvProjectTable.PROJECTSTATE = 0
GO

