USE [VLT_AX500105_P]
GO

IF EXISTS (
		SELECT 1
		FROM sys.VIEWS
		WHERE NAME = 'VLT_DB_POWERBI_VLT_SALESAREA'
			AND type = 'V'
	)
	DROP VIEW [dbo].[VLT_DB_POWERBI_VLT_SALESAREA]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VLT_DB_POWERBI_VLT_SALESAREA]
AS
	SELECT SalesArea.SALESAREAID,
			SalesArea.DESCRIPTION,
			SalesArea.SALESAREAID + SalesArea.DATAAREAID AS SalesAreaPK
	FROM dbo.VLT_SALESAREA AS SalesArea
	WHERE SalesArea.DATAAREAID = '100'
GO