IF OBJECT_ID(N'dbo.VLT_DB_GETDATETIMEWITHTIMEZONE', N'FN') IS NOT NULL
	DROP FUNCTION VLT_DB_GETDATETIMEWITHTIMEZONE;
GO

CREATE FUNCTION dbo.VLT_DB_GETDATETIMEWITHTIMEZONE
	(
		@dateTimeValue DATETIME
	)
RETURNS DATETIME
AS
	-- Returns the stock level for the product.  
	BEGIN
		DECLARE @ret DATETIME;
		SELECT @ret = CONVERT(DATETIME, SWITCHOFFSET(CONVERT(DATETIMEOFFSET, @dateTimeValue), DATENAME(TZOFFSET, SYSDATETIMEOFFSET())))
		RETURN @ret;
	END; 
